/**
 * generated by Xtext 2.20.0
 */
package br.ufes.inf.ontouml.ontoumlprime.dsl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Collective Universal</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.ufes.inf.ontouml.ontoumlprime.dsl.CollectiveUniversal#isIsExtensional <em>Is Extensional</em>}</li>
 *   <li>{@link br.ufes.inf.ontouml.ontoumlprime.dsl.CollectiveUniversal#getName <em>Name</em>}</li>
 *   <li>{@link br.ufes.inf.ontouml.ontoumlprime.dsl.CollectiveUniversal#getCharacterizedBy <em>Characterized By</em>}</li>
 * </ul>
 *
 * @see br.ufes.inf.ontouml.ontoumlprime.dsl.DslPackage#getCollectiveUniversal()
 * @model
 * @generated
 */
public interface CollectiveUniversal extends PackageableElement, EndurantUniversal, Universal, SubstantialUniversal
{
  /**
   * Returns the value of the '<em><b>Is Extensional</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Is Extensional</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Is Extensional</em>' attribute.
   * @see #setIsExtensional(boolean)
   * @see br.ufes.inf.ontouml.ontoumlprime.dsl.DslPackage#getCollectiveUniversal_IsExtensional()
   * @model
   * @generated
   */
  boolean isIsExtensional();

  /**
   * Sets the value of the '{@link br.ufes.inf.ontouml.ontoumlprime.dsl.CollectiveUniversal#isIsExtensional <em>Is Extensional</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Is Extensional</em>' attribute.
   * @see #isIsExtensional()
   * @generated
   */
  void setIsExtensional(boolean value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see br.ufes.inf.ontouml.ontoumlprime.dsl.DslPackage#getCollectiveUniversal_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link br.ufes.inf.ontouml.ontoumlprime.dsl.CollectiveUniversal#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Characterized By</b></em>' containment reference list.
   * The list contents are of type {@link br.ufes.inf.ontouml.ontoumlprime.dsl.Characterization}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Characterized By</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Characterized By</em>' containment reference list.
   * @see br.ufes.inf.ontouml.ontoumlprime.dsl.DslPackage#getCollectiveUniversal_CharacterizedBy()
   * @model containment="true"
   * @generated
   */
  EList<Characterization> getCharacterizedBy();

} // CollectiveUniversal
