/**
 * generated by Xtext 2.20.0
 */
package br.ufes.inf.ontouml.ontoumlprime.dsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Endurant Universal</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see br.ufes.inf.ontouml.ontoumlprime.dsl.DslPackage#getEndurantUniversal()
 * @model
 * @generated
 */
public interface EndurantUniversal extends EObject
{
} // EndurantUniversal
