/**
 * generated by Xtext 2.20.0
 */
package br.ufes.inf.ontouml.ontoumlprime.dsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Externally Dependent Universal</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see br.ufes.inf.ontouml.ontoumlprime.dsl.DslPackage#getExternallyDependentUniversal()
 * @model
 * @generated
 */
public interface ExternallyDependentUniversal extends EObject
{
} // ExternallyDependentUniversal
