/**
 * generated by Xtext 2.20.0
 */
package br.ufes.inf.ontouml.ontoumlprime.dsl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Generalization Set</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.ufes.inf.ontouml.ontoumlprime.dsl.GeneralizationSet#isIsCovering <em>Is Covering</em>}</li>
 *   <li>{@link br.ufes.inf.ontouml.ontoumlprime.dsl.GeneralizationSet#getName <em>Name</em>}</li>
 *   <li>{@link br.ufes.inf.ontouml.ontoumlprime.dsl.GeneralizationSet#getSpecializedUniversal <em>Specialized Universal</em>}</li>
 *   <li>{@link br.ufes.inf.ontouml.ontoumlprime.dsl.GeneralizationSet#getSpecializingUniversals <em>Specializing Universals</em>}</li>
 * </ul>
 *
 * @see br.ufes.inf.ontouml.ontoumlprime.dsl.DslPackage#getGeneralizationSet()
 * @model
 * @generated
 */
public interface GeneralizationSet extends PackageableElement
{
  /**
   * Returns the value of the '<em><b>Is Covering</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Is Covering</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Is Covering</em>' attribute.
   * @see #setIsCovering(boolean)
   * @see br.ufes.inf.ontouml.ontoumlprime.dsl.DslPackage#getGeneralizationSet_IsCovering()
   * @model
   * @generated
   */
  boolean isIsCovering();

  /**
   * Sets the value of the '{@link br.ufes.inf.ontouml.ontoumlprime.dsl.GeneralizationSet#isIsCovering <em>Is Covering</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Is Covering</em>' attribute.
   * @see #isIsCovering()
   * @generated
   */
  void setIsCovering(boolean value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see br.ufes.inf.ontouml.ontoumlprime.dsl.DslPackage#getGeneralizationSet_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link br.ufes.inf.ontouml.ontoumlprime.dsl.GeneralizationSet#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Specialized Universal</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Specialized Universal</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Specialized Universal</em>' reference.
   * @see #setSpecializedUniversal(Universal)
   * @see br.ufes.inf.ontouml.ontoumlprime.dsl.DslPackage#getGeneralizationSet_SpecializedUniversal()
   * @model
   * @generated
   */
  Universal getSpecializedUniversal();

  /**
   * Sets the value of the '{@link br.ufes.inf.ontouml.ontoumlprime.dsl.GeneralizationSet#getSpecializedUniversal <em>Specialized Universal</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Specialized Universal</em>' reference.
   * @see #getSpecializedUniversal()
   * @generated
   */
  void setSpecializedUniversal(Universal value);

  /**
   * Returns the value of the '<em><b>Specializing Universals</b></em>' reference list.
   * The list contents are of type {@link br.ufes.inf.ontouml.ontoumlprime.dsl.Universal}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Specializing Universals</em>' reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Specializing Universals</em>' reference list.
   * @see br.ufes.inf.ontouml.ontoumlprime.dsl.DslPackage#getGeneralizationSet_SpecializingUniversals()
   * @model
   * @generated
   */
  EList<Universal> getSpecializingUniversals();

} // GeneralizationSet
