/**
 * generated by Xtext 2.20.0
 */
package br.ufes.inf.ontouml.ontoumlprime.dsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Membership Relation</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.ufes.inf.ontouml.ontoumlprime.dsl.MembershipRelation#isPartIsShareable <em>Part Is Shareable</em>}</li>
 * </ul>
 *
 * @see br.ufes.inf.ontouml.ontoumlprime.dsl.DslPackage#getMembershipRelation()
 * @model
 * @generated
 */
public interface MembershipRelation extends MeronymicRelation
{
  /**
   * Returns the value of the '<em><b>Part Is Shareable</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Part Is Shareable</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Part Is Shareable</em>' attribute.
   * @see #setPartIsShareable(boolean)
   * @see br.ufes.inf.ontouml.ontoumlprime.dsl.DslPackage#getMembershipRelation_PartIsShareable()
   * @model
   * @generated
   */
  boolean isPartIsShareable();

  /**
   * Sets the value of the '{@link br.ufes.inf.ontouml.ontoumlprime.dsl.MembershipRelation#isPartIsShareable <em>Part Is Shareable</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Part Is Shareable</em>' attribute.
   * @see #isPartIsShareable()
   * @generated
   */
  void setPartIsShareable(boolean value);

} // MembershipRelation
