/**
 * generated by Xtext 2.20.0
 */
package br.ufes.inf.ontouml.ontoumlprime.dsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Meronymic Relation</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.ufes.inf.ontouml.ontoumlprime.dsl.MeronymicRelation#isPartIsEssential <em>Part Is Essential</em>}</li>
 *   <li>{@link br.ufes.inf.ontouml.ontoumlprime.dsl.MeronymicRelation#isPartIsInseparable <em>Part Is Inseparable</em>}</li>
 *   <li>{@link br.ufes.inf.ontouml.ontoumlprime.dsl.MeronymicRelation#isPartIsImmutable <em>Part Is Immutable</em>}</li>
 *   <li>{@link br.ufes.inf.ontouml.ontoumlprime.dsl.MeronymicRelation#getPart <em>Part</em>}</li>
 *   <li>{@link br.ufes.inf.ontouml.ontoumlprime.dsl.MeronymicRelation#getSourceLowerBound <em>Source Lower Bound</em>}</li>
 *   <li>{@link br.ufes.inf.ontouml.ontoumlprime.dsl.MeronymicRelation#getSourceUpperBound <em>Source Upper Bound</em>}</li>
 *   <li>{@link br.ufes.inf.ontouml.ontoumlprime.dsl.MeronymicRelation#getWhole <em>Whole</em>}</li>
 *   <li>{@link br.ufes.inf.ontouml.ontoumlprime.dsl.MeronymicRelation#getTargetLowerBound <em>Target Lower Bound</em>}</li>
 *   <li>{@link br.ufes.inf.ontouml.ontoumlprime.dsl.MeronymicRelation#getTargetUpperBound <em>Target Upper Bound</em>}</li>
 * </ul>
 *
 * @see br.ufes.inf.ontouml.ontoumlprime.dsl.DslPackage#getMeronymicRelation()
 * @model
 * @generated
 */
public interface MeronymicRelation extends PackageableElement
{
  /**
   * Returns the value of the '<em><b>Part Is Essential</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Part Is Essential</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Part Is Essential</em>' attribute.
   * @see #setPartIsEssential(boolean)
   * @see br.ufes.inf.ontouml.ontoumlprime.dsl.DslPackage#getMeronymicRelation_PartIsEssential()
   * @model
   * @generated
   */
  boolean isPartIsEssential();

  /**
   * Sets the value of the '{@link br.ufes.inf.ontouml.ontoumlprime.dsl.MeronymicRelation#isPartIsEssential <em>Part Is Essential</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Part Is Essential</em>' attribute.
   * @see #isPartIsEssential()
   * @generated
   */
  void setPartIsEssential(boolean value);

  /**
   * Returns the value of the '<em><b>Part Is Inseparable</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Part Is Inseparable</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Part Is Inseparable</em>' attribute.
   * @see #setPartIsInseparable(boolean)
   * @see br.ufes.inf.ontouml.ontoumlprime.dsl.DslPackage#getMeronymicRelation_PartIsInseparable()
   * @model
   * @generated
   */
  boolean isPartIsInseparable();

  /**
   * Sets the value of the '{@link br.ufes.inf.ontouml.ontoumlprime.dsl.MeronymicRelation#isPartIsInseparable <em>Part Is Inseparable</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Part Is Inseparable</em>' attribute.
   * @see #isPartIsInseparable()
   * @generated
   */
  void setPartIsInseparable(boolean value);

  /**
   * Returns the value of the '<em><b>Part Is Immutable</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Part Is Immutable</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Part Is Immutable</em>' attribute.
   * @see #setPartIsImmutable(boolean)
   * @see br.ufes.inf.ontouml.ontoumlprime.dsl.DslPackage#getMeronymicRelation_PartIsImmutable()
   * @model
   * @generated
   */
  boolean isPartIsImmutable();

  /**
   * Sets the value of the '{@link br.ufes.inf.ontouml.ontoumlprime.dsl.MeronymicRelation#isPartIsImmutable <em>Part Is Immutable</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Part Is Immutable</em>' attribute.
   * @see #isPartIsImmutable()
   * @generated
   */
  void setPartIsImmutable(boolean value);

  /**
   * Returns the value of the '<em><b>Part</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Part</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Part</em>' reference.
   * @see #setPart(SubstantialUniversal)
   * @see br.ufes.inf.ontouml.ontoumlprime.dsl.DslPackage#getMeronymicRelation_Part()
   * @model
   * @generated
   */
  SubstantialUniversal getPart();

  /**
   * Sets the value of the '{@link br.ufes.inf.ontouml.ontoumlprime.dsl.MeronymicRelation#getPart <em>Part</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Part</em>' reference.
   * @see #getPart()
   * @generated
   */
  void setPart(SubstantialUniversal value);

  /**
   * Returns the value of the '<em><b>Source Lower Bound</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Source Lower Bound</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Source Lower Bound</em>' attribute.
   * @see #setSourceLowerBound(int)
   * @see br.ufes.inf.ontouml.ontoumlprime.dsl.DslPackage#getMeronymicRelation_SourceLowerBound()
   * @model
   * @generated
   */
  int getSourceLowerBound();

  /**
   * Sets the value of the '{@link br.ufes.inf.ontouml.ontoumlprime.dsl.MeronymicRelation#getSourceLowerBound <em>Source Lower Bound</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Source Lower Bound</em>' attribute.
   * @see #getSourceLowerBound()
   * @generated
   */
  void setSourceLowerBound(int value);

  /**
   * Returns the value of the '<em><b>Source Upper Bound</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Source Upper Bound</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Source Upper Bound</em>' attribute.
   * @see #setSourceUpperBound(int)
   * @see br.ufes.inf.ontouml.ontoumlprime.dsl.DslPackage#getMeronymicRelation_SourceUpperBound()
   * @model
   * @generated
   */
  int getSourceUpperBound();

  /**
   * Sets the value of the '{@link br.ufes.inf.ontouml.ontoumlprime.dsl.MeronymicRelation#getSourceUpperBound <em>Source Upper Bound</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Source Upper Bound</em>' attribute.
   * @see #getSourceUpperBound()
   * @generated
   */
  void setSourceUpperBound(int value);

  /**
   * Returns the value of the '<em><b>Whole</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Whole</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Whole</em>' reference.
   * @see #setWhole(SubstantialUniversal)
   * @see br.ufes.inf.ontouml.ontoumlprime.dsl.DslPackage#getMeronymicRelation_Whole()
   * @model
   * @generated
   */
  SubstantialUniversal getWhole();

  /**
   * Sets the value of the '{@link br.ufes.inf.ontouml.ontoumlprime.dsl.MeronymicRelation#getWhole <em>Whole</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Whole</em>' reference.
   * @see #getWhole()
   * @generated
   */
  void setWhole(SubstantialUniversal value);

  /**
   * Returns the value of the '<em><b>Target Lower Bound</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Target Lower Bound</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Target Lower Bound</em>' attribute.
   * @see #setTargetLowerBound(int)
   * @see br.ufes.inf.ontouml.ontoumlprime.dsl.DslPackage#getMeronymicRelation_TargetLowerBound()
   * @model
   * @generated
   */
  int getTargetLowerBound();

  /**
   * Sets the value of the '{@link br.ufes.inf.ontouml.ontoumlprime.dsl.MeronymicRelation#getTargetLowerBound <em>Target Lower Bound</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Target Lower Bound</em>' attribute.
   * @see #getTargetLowerBound()
   * @generated
   */
  void setTargetLowerBound(int value);

  /**
   * Returns the value of the '<em><b>Target Upper Bound</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Target Upper Bound</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Target Upper Bound</em>' attribute.
   * @see #setTargetUpperBound(int)
   * @see br.ufes.inf.ontouml.ontoumlprime.dsl.DslPackage#getMeronymicRelation_TargetUpperBound()
   * @model
   * @generated
   */
  int getTargetUpperBound();

  /**
   * Sets the value of the '{@link br.ufes.inf.ontouml.ontoumlprime.dsl.MeronymicRelation#getTargetUpperBound <em>Target Upper Bound</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Target Upper Bound</em>' attribute.
   * @see #getTargetUpperBound()
   * @generated
   */
  void setTargetUpperBound(int value);

} // MeronymicRelation
