/**
 * generated by Xtext 2.20.0
 */
package br.ufes.inf.ontouml.ontoumlprime.dsl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>nAry Material Relation</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.ufes.inf.ontouml.ontoumlprime.dsl.nAryMaterialRelation#getDerivedFrom <em>Derived From</em>}</li>
 *   <li>{@link br.ufes.inf.ontouml.ontoumlprime.dsl.nAryMaterialRelation#getName <em>Name</em>}</li>
 *   <li>{@link br.ufes.inf.ontouml.ontoumlprime.dsl.nAryMaterialRelation#getTargetRelata <em>Target Relata</em>}</li>
 *   <li>{@link br.ufes.inf.ontouml.ontoumlprime.dsl.nAryMaterialRelation#getSourceLowerBound <em>Source Lower Bound</em>}</li>
 *   <li>{@link br.ufes.inf.ontouml.ontoumlprime.dsl.nAryMaterialRelation#getSourceUpperBound <em>Source Upper Bound</em>}</li>
 * </ul>
 *
 * @see br.ufes.inf.ontouml.ontoumlprime.dsl.DslPackage#getnAryMaterialRelation()
 * @model
 * @generated
 */
public interface nAryMaterialRelation extends PackageableElement
{
  /**
   * Returns the value of the '<em><b>Derived From</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Derived From</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Derived From</em>' reference.
   * @see #setDerivedFrom(RelatorUniversal)
   * @see br.ufes.inf.ontouml.ontoumlprime.dsl.DslPackage#getnAryMaterialRelation_DerivedFrom()
   * @model
   * @generated
   */
  RelatorUniversal getDerivedFrom();

  /**
   * Sets the value of the '{@link br.ufes.inf.ontouml.ontoumlprime.dsl.nAryMaterialRelation#getDerivedFrom <em>Derived From</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Derived From</em>' reference.
   * @see #getDerivedFrom()
   * @generated
   */
  void setDerivedFrom(RelatorUniversal value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see br.ufes.inf.ontouml.ontoumlprime.dsl.DslPackage#getnAryMaterialRelation_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link br.ufes.inf.ontouml.ontoumlprime.dsl.nAryMaterialRelation#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Target Relata</b></em>' reference list.
   * The list contents are of type {@link br.ufes.inf.ontouml.ontoumlprime.dsl.ExternallyDependentUniversal}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Target Relata</em>' reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Target Relata</em>' reference list.
   * @see br.ufes.inf.ontouml.ontoumlprime.dsl.DslPackage#getnAryMaterialRelation_TargetRelata()
   * @model
   * @generated
   */
  EList<ExternallyDependentUniversal> getTargetRelata();

  /**
   * Returns the value of the '<em><b>Source Lower Bound</b></em>' attribute list.
   * The list contents are of type {@link java.lang.Integer}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Source Lower Bound</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Source Lower Bound</em>' attribute list.
   * @see br.ufes.inf.ontouml.ontoumlprime.dsl.DslPackage#getnAryMaterialRelation_SourceLowerBound()
   * @model unique="false"
   * @generated
   */
  EList<Integer> getSourceLowerBound();

  /**
   * Returns the value of the '<em><b>Source Upper Bound</b></em>' attribute list.
   * The list contents are of type {@link java.lang.Integer}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Source Upper Bound</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Source Upper Bound</em>' attribute list.
   * @see br.ufes.inf.ontouml.ontoumlprime.dsl.DslPackage#getnAryMaterialRelation_SourceUpperBound()
   * @model unique="false"
   * @generated
   */
  EList<Integer> getSourceUpperBound();

} // nAryMaterialRelation
