/**
 * generated by Xtext 2.20.0
 */
package br.ufes.inf.ontouml.ontoumlprime.dsl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Quality Universal</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.ufes.inf.ontouml.ontoumlprime.dsl.QualityUniversal#getName <em>Name</em>}</li>
 *   <li>{@link br.ufes.inf.ontouml.ontoumlprime.dsl.QualityUniversal#getCharacterization <em>Characterization</em>}</li>
 *   <li>{@link br.ufes.inf.ontouml.ontoumlprime.dsl.QualityUniversal#getDatatypes <em>Datatypes</em>}</li>
 *   <li>{@link br.ufes.inf.ontouml.ontoumlprime.dsl.QualityUniversal#getCharacterizedBy <em>Characterized By</em>}</li>
 * </ul>
 *
 * @see br.ufes.inf.ontouml.ontoumlprime.dsl.DslPackage#getQualityUniversal()
 * @model
 * @generated
 */
public interface QualityUniversal extends PackageableElement, EndurantUniversal, Universal, IntrinsicMomentUniversal
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see br.ufes.inf.ontouml.ontoumlprime.dsl.DslPackage#getQualityUniversal_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link br.ufes.inf.ontouml.ontoumlprime.dsl.QualityUniversal#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Characterization</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Characterization</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Characterization</em>' reference.
   * @see #setCharacterization(Characterization)
   * @see br.ufes.inf.ontouml.ontoumlprime.dsl.DslPackage#getQualityUniversal_Characterization()
   * @model
   * @generated
   */
  Characterization getCharacterization();

  /**
   * Sets the value of the '{@link br.ufes.inf.ontouml.ontoumlprime.dsl.QualityUniversal#getCharacterization <em>Characterization</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Characterization</em>' reference.
   * @see #getCharacterization()
   * @generated
   */
  void setCharacterization(Characterization value);

  /**
   * Returns the value of the '<em><b>Datatypes</b></em>' reference list.
   * The list contents are of type {@link br.ufes.inf.ontouml.ontoumlprime.dsl.DataType}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Datatypes</em>' reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Datatypes</em>' reference list.
   * @see br.ufes.inf.ontouml.ontoumlprime.dsl.DslPackage#getQualityUniversal_Datatypes()
   * @model
   * @generated
   */
  EList<DataType> getDatatypes();

  /**
   * Returns the value of the '<em><b>Characterized By</b></em>' containment reference list.
   * The list contents are of type {@link br.ufes.inf.ontouml.ontoumlprime.dsl.Characterization}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Characterized By</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Characterized By</em>' containment reference list.
   * @see br.ufes.inf.ontouml.ontoumlprime.dsl.DslPackage#getQualityUniversal_CharacterizedBy()
   * @model containment="true"
   * @generated
   */
  EList<Characterization> getCharacterizedBy();

} // QualityUniversal
