/**
 * generated by Xtext 2.20.0
 */
package br.ufes.inf.ontouml.ontoumlprime.dsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Sub Quantity Relation</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see br.ufes.inf.ontouml.ontoumlprime.dsl.DslPackage#getSubQuantityRelation()
 * @model
 * @generated
 */
public interface SubQuantityRelation extends MeronymicRelation
{
} // SubQuantityRelation
