/*
 * generated by Xtext 2.20.0
 */
package br.ufes.inf.ontouml.ontoumlprime.ui;

import br.ufes.inf.ontouml.ontoumlprime.ui.internal.OntoumlprimeActivator;
import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class DslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(OntoumlprimeActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		OntoumlprimeActivator activator = OntoumlprimeActivator.getInstance();
		return activator != null ? activator.getInjector(OntoumlprimeActivator.BR_UFES_INF_ONTOUML_ONTOUMLPRIME_DSL) : null;
	}

}
