/*
 * generated by Xtext 2.20.0
 */
package br.ufes.inf.ontouml.ontoumlprime.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class DslUiModule extends AbstractDslUiModule {

	public DslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
