/**
 * generated by Xtext 2.20.0
 */
package br.ufes.inf.ontouml.ontoumlprime.dsl.impl;

import br.ufes.inf.ontouml.ontoumlprime.dsl.BinaryFormalRelation;
import br.ufes.inf.ontouml.ontoumlprime.dsl.DslPackage;
import br.ufes.inf.ontouml.ontoumlprime.dsl.Universal;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Binary Formal Relation</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link br.ufes.inf.ontouml.ontoumlprime.dsl.impl.BinaryFormalRelationImpl#getSource <em>Source</em>}</li>
 *   <li>{@link br.ufes.inf.ontouml.ontoumlprime.dsl.impl.BinaryFormalRelationImpl#getSourceLowerBound <em>Source Lower Bound</em>}</li>
 *   <li>{@link br.ufes.inf.ontouml.ontoumlprime.dsl.impl.BinaryFormalRelationImpl#getSourceUpperBound <em>Source Upper Bound</em>}</li>
 *   <li>{@link br.ufes.inf.ontouml.ontoumlprime.dsl.impl.BinaryFormalRelationImpl#getName <em>Name</em>}</li>
 *   <li>{@link br.ufes.inf.ontouml.ontoumlprime.dsl.impl.BinaryFormalRelationImpl#getTarget <em>Target</em>}</li>
 *   <li>{@link br.ufes.inf.ontouml.ontoumlprime.dsl.impl.BinaryFormalRelationImpl#getTargetLowerBound <em>Target Lower Bound</em>}</li>
 *   <li>{@link br.ufes.inf.ontouml.ontoumlprime.dsl.impl.BinaryFormalRelationImpl#getTargetUpperBound <em>Target Upper Bound</em>}</li>
 * </ul>
 *
 * @generated
 */
public class BinaryFormalRelationImpl extends PackageableElementImpl implements BinaryFormalRelation
{
  /**
   * The cached value of the '{@link #getSource() <em>Source</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSource()
   * @generated
   * @ordered
   */
  protected Universal source;

  /**
   * The default value of the '{@link #getSourceLowerBound() <em>Source Lower Bound</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSourceLowerBound()
   * @generated
   * @ordered
   */
  protected static final int SOURCE_LOWER_BOUND_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getSourceLowerBound() <em>Source Lower Bound</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSourceLowerBound()
   * @generated
   * @ordered
   */
  protected int sourceLowerBound = SOURCE_LOWER_BOUND_EDEFAULT;

  /**
   * The default value of the '{@link #getSourceUpperBound() <em>Source Upper Bound</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSourceUpperBound()
   * @generated
   * @ordered
   */
  protected static final int SOURCE_UPPER_BOUND_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getSourceUpperBound() <em>Source Upper Bound</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSourceUpperBound()
   * @generated
   * @ordered
   */
  protected int sourceUpperBound = SOURCE_UPPER_BOUND_EDEFAULT;

  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getTarget() <em>Target</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTarget()
   * @generated
   * @ordered
   */
  protected Universal target;

  /**
   * The default value of the '{@link #getTargetLowerBound() <em>Target Lower Bound</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTargetLowerBound()
   * @generated
   * @ordered
   */
  protected static final int TARGET_LOWER_BOUND_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getTargetLowerBound() <em>Target Lower Bound</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTargetLowerBound()
   * @generated
   * @ordered
   */
  protected int targetLowerBound = TARGET_LOWER_BOUND_EDEFAULT;

  /**
   * The default value of the '{@link #getTargetUpperBound() <em>Target Upper Bound</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTargetUpperBound()
   * @generated
   * @ordered
   */
  protected static final int TARGET_UPPER_BOUND_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getTargetUpperBound() <em>Target Upper Bound</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTargetUpperBound()
   * @generated
   * @ordered
   */
  protected int targetUpperBound = TARGET_UPPER_BOUND_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected BinaryFormalRelationImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DslPackage.Literals.BINARY_FORMAL_RELATION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Universal getSource()
  {
    if (source != null && source.eIsProxy())
    {
      InternalEObject oldSource = (InternalEObject)source;
      source = (Universal)eResolveProxy(oldSource);
      if (source != oldSource)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, DslPackage.BINARY_FORMAL_RELATION__SOURCE, oldSource, source));
      }
    }
    return source;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Universal basicGetSource()
  {
    return source;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setSource(Universal newSource)
  {
    Universal oldSource = source;
    source = newSource;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DslPackage.BINARY_FORMAL_RELATION__SOURCE, oldSource, source));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getSourceLowerBound()
  {
    return sourceLowerBound;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setSourceLowerBound(int newSourceLowerBound)
  {
    int oldSourceLowerBound = sourceLowerBound;
    sourceLowerBound = newSourceLowerBound;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DslPackage.BINARY_FORMAL_RELATION__SOURCE_LOWER_BOUND, oldSourceLowerBound, sourceLowerBound));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getSourceUpperBound()
  {
    return sourceUpperBound;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setSourceUpperBound(int newSourceUpperBound)
  {
    int oldSourceUpperBound = sourceUpperBound;
    sourceUpperBound = newSourceUpperBound;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DslPackage.BINARY_FORMAL_RELATION__SOURCE_UPPER_BOUND, oldSourceUpperBound, sourceUpperBound));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DslPackage.BINARY_FORMAL_RELATION__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Universal getTarget()
  {
    if (target != null && target.eIsProxy())
    {
      InternalEObject oldTarget = (InternalEObject)target;
      target = (Universal)eResolveProxy(oldTarget);
      if (target != oldTarget)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, DslPackage.BINARY_FORMAL_RELATION__TARGET, oldTarget, target));
      }
    }
    return target;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Universal basicGetTarget()
  {
    return target;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setTarget(Universal newTarget)
  {
    Universal oldTarget = target;
    target = newTarget;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DslPackage.BINARY_FORMAL_RELATION__TARGET, oldTarget, target));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getTargetLowerBound()
  {
    return targetLowerBound;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setTargetLowerBound(int newTargetLowerBound)
  {
    int oldTargetLowerBound = targetLowerBound;
    targetLowerBound = newTargetLowerBound;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DslPackage.BINARY_FORMAL_RELATION__TARGET_LOWER_BOUND, oldTargetLowerBound, targetLowerBound));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getTargetUpperBound()
  {
    return targetUpperBound;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setTargetUpperBound(int newTargetUpperBound)
  {
    int oldTargetUpperBound = targetUpperBound;
    targetUpperBound = newTargetUpperBound;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DslPackage.BINARY_FORMAL_RELATION__TARGET_UPPER_BOUND, oldTargetUpperBound, targetUpperBound));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case DslPackage.BINARY_FORMAL_RELATION__SOURCE:
        if (resolve) return getSource();
        return basicGetSource();
      case DslPackage.BINARY_FORMAL_RELATION__SOURCE_LOWER_BOUND:
        return getSourceLowerBound();
      case DslPackage.BINARY_FORMAL_RELATION__SOURCE_UPPER_BOUND:
        return getSourceUpperBound();
      case DslPackage.BINARY_FORMAL_RELATION__NAME:
        return getName();
      case DslPackage.BINARY_FORMAL_RELATION__TARGET:
        if (resolve) return getTarget();
        return basicGetTarget();
      case DslPackage.BINARY_FORMAL_RELATION__TARGET_LOWER_BOUND:
        return getTargetLowerBound();
      case DslPackage.BINARY_FORMAL_RELATION__TARGET_UPPER_BOUND:
        return getTargetUpperBound();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case DslPackage.BINARY_FORMAL_RELATION__SOURCE:
        setSource((Universal)newValue);
        return;
      case DslPackage.BINARY_FORMAL_RELATION__SOURCE_LOWER_BOUND:
        setSourceLowerBound((Integer)newValue);
        return;
      case DslPackage.BINARY_FORMAL_RELATION__SOURCE_UPPER_BOUND:
        setSourceUpperBound((Integer)newValue);
        return;
      case DslPackage.BINARY_FORMAL_RELATION__NAME:
        setName((String)newValue);
        return;
      case DslPackage.BINARY_FORMAL_RELATION__TARGET:
        setTarget((Universal)newValue);
        return;
      case DslPackage.BINARY_FORMAL_RELATION__TARGET_LOWER_BOUND:
        setTargetLowerBound((Integer)newValue);
        return;
      case DslPackage.BINARY_FORMAL_RELATION__TARGET_UPPER_BOUND:
        setTargetUpperBound((Integer)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case DslPackage.BINARY_FORMAL_RELATION__SOURCE:
        setSource((Universal)null);
        return;
      case DslPackage.BINARY_FORMAL_RELATION__SOURCE_LOWER_BOUND:
        setSourceLowerBound(SOURCE_LOWER_BOUND_EDEFAULT);
        return;
      case DslPackage.BINARY_FORMAL_RELATION__SOURCE_UPPER_BOUND:
        setSourceUpperBound(SOURCE_UPPER_BOUND_EDEFAULT);
        return;
      case DslPackage.BINARY_FORMAL_RELATION__NAME:
        setName(NAME_EDEFAULT);
        return;
      case DslPackage.BINARY_FORMAL_RELATION__TARGET:
        setTarget((Universal)null);
        return;
      case DslPackage.BINARY_FORMAL_RELATION__TARGET_LOWER_BOUND:
        setTargetLowerBound(TARGET_LOWER_BOUND_EDEFAULT);
        return;
      case DslPackage.BINARY_FORMAL_RELATION__TARGET_UPPER_BOUND:
        setTargetUpperBound(TARGET_UPPER_BOUND_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case DslPackage.BINARY_FORMAL_RELATION__SOURCE:
        return source != null;
      case DslPackage.BINARY_FORMAL_RELATION__SOURCE_LOWER_BOUND:
        return sourceLowerBound != SOURCE_LOWER_BOUND_EDEFAULT;
      case DslPackage.BINARY_FORMAL_RELATION__SOURCE_UPPER_BOUND:
        return sourceUpperBound != SOURCE_UPPER_BOUND_EDEFAULT;
      case DslPackage.BINARY_FORMAL_RELATION__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case DslPackage.BINARY_FORMAL_RELATION__TARGET:
        return target != null;
      case DslPackage.BINARY_FORMAL_RELATION__TARGET_LOWER_BOUND:
        return targetLowerBound != TARGET_LOWER_BOUND_EDEFAULT;
      case DslPackage.BINARY_FORMAL_RELATION__TARGET_UPPER_BOUND:
        return targetUpperBound != TARGET_UPPER_BOUND_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (sourceLowerBound: ");
    result.append(sourceLowerBound);
    result.append(", sourceUpperBound: ");
    result.append(sourceUpperBound);
    result.append(", name: ");
    result.append(name);
    result.append(", targetLowerBound: ");
    result.append(targetLowerBound);
    result.append(", targetUpperBound: ");
    result.append(targetUpperBound);
    result.append(')');
    return result.toString();
  }

} //BinaryFormalRelationImpl
