/**
 * generated by Xtext 2.20.0
 */
package br.ufes.inf.ontouml.ontoumlprime.dsl.impl;

import br.ufes.inf.ontouml.ontoumlprime.dsl.BinaryFormalRelation;
import br.ufes.inf.ontouml.ontoumlprime.dsl.BinaryMaterialRelation;
import br.ufes.inf.ontouml.ontoumlprime.dsl.Category;
import br.ufes.inf.ontouml.ontoumlprime.dsl.Characterization;
import br.ufes.inf.ontouml.ontoumlprime.dsl.CollectiveUniversal;
import br.ufes.inf.ontouml.ontoumlprime.dsl.ComplexDataType;
import br.ufes.inf.ontouml.ontoumlprime.dsl.ComponentOfRelation;
import br.ufes.inf.ontouml.ontoumlprime.dsl.DataType;
import br.ufes.inf.ontouml.ontoumlprime.dsl.DataTypeAttribute;
import br.ufes.inf.ontouml.ontoumlprime.dsl.DslFactory;
import br.ufes.inf.ontouml.ontoumlprime.dsl.DslPackage;
import br.ufes.inf.ontouml.ontoumlprime.dsl.EndurantUniversal;
import br.ufes.inf.ontouml.ontoumlprime.dsl.Enumeration;
import br.ufes.inf.ontouml.ontoumlprime.dsl.ExternallyDependentUniversal;
import br.ufes.inf.ontouml.ontoumlprime.dsl.GeneralizationSet;
import br.ufes.inf.ontouml.ontoumlprime.dsl.IntrinsicMomentUniversal;
import br.ufes.inf.ontouml.ontoumlprime.dsl.Kind;
import br.ufes.inf.ontouml.ontoumlprime.dsl.Mediation;
import br.ufes.inf.ontouml.ontoumlprime.dsl.MembershipRelation;
import br.ufes.inf.ontouml.ontoumlprime.dsl.MeronymicRelation;
import br.ufes.inf.ontouml.ontoumlprime.dsl.Mixin;
import br.ufes.inf.ontouml.ontoumlprime.dsl.ModeUniversal;
import br.ufes.inf.ontouml.ontoumlprime.dsl.Model;
import br.ufes.inf.ontouml.ontoumlprime.dsl.PackageableElement;
import br.ufes.inf.ontouml.ontoumlprime.dsl.Phase;
import br.ufes.inf.ontouml.ontoumlprime.dsl.PrimitiveDataType;
import br.ufes.inf.ontouml.ontoumlprime.dsl.PrimitiveDataTypeType;
import br.ufes.inf.ontouml.ontoumlprime.dsl.QualityUniversal;
import br.ufes.inf.ontouml.ontoumlprime.dsl.QuantityUniversal;
import br.ufes.inf.ontouml.ontoumlprime.dsl.RelatorUniversal;
import br.ufes.inf.ontouml.ontoumlprime.dsl.Role;
import br.ufes.inf.ontouml.ontoumlprime.dsl.RoleMixin;
import br.ufes.inf.ontouml.ontoumlprime.dsl.SubCollectionRelation;
import br.ufes.inf.ontouml.ontoumlprime.dsl.SubKind;
import br.ufes.inf.ontouml.ontoumlprime.dsl.SubQuantityRelation;
import br.ufes.inf.ontouml.ontoumlprime.dsl.SubstantialUniversal;
import br.ufes.inf.ontouml.ontoumlprime.dsl.Universal;
import br.ufes.inf.ontouml.ontoumlprime.dsl.nAryFormalRelation;
import br.ufes.inf.ontouml.ontoumlprime.dsl.nAryMaterialRelation;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class DslFactoryImpl extends EFactoryImpl implements DslFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static DslFactory init()
  {
    try
    {
      DslFactory theDslFactory = (DslFactory)EPackage.Registry.INSTANCE.getEFactory(DslPackage.eNS_URI);
      if (theDslFactory != null)
      {
        return theDslFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new DslFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public DslFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case DslPackage.MODEL: return createModel();
      case DslPackage.PACKAGEABLE_ELEMENT: return createPackageableElement();
      case DslPackage.ENDURANT_UNIVERSAL: return createEndurantUniversal();
      case DslPackage.UNIVERSAL: return createUniversal();
      case DslPackage.DATA_TYPE: return createDataType();
      case DslPackage.INTRINSIC_MOMENT_UNIVERSAL: return createIntrinsicMomentUniversal();
      case DslPackage.EXTERNALLY_DEPENDENT_UNIVERSAL: return createExternallyDependentUniversal();
      case DslPackage.PACKAGE: return createPackage();
      case DslPackage.GENERALIZATION_SET: return createGeneralizationSet();
      case DslPackage.PRIMITIVE_DATA_TYPE: return createPrimitiveDataType();
      case DslPackage.COMPLEX_DATA_TYPE: return createComplexDataType();
      case DslPackage.ENUMERATION: return createEnumeration();
      case DslPackage.SUBSTANTIAL_UNIVERSAL: return createSubstantialUniversal();
      case DslPackage.MERONYMIC_RELATION: return createMeronymicRelation();
      case DslPackage.COMPONENT_OF_RELATION: return createComponentOfRelation();
      case DslPackage.MEMBERSHIP_RELATION: return createMembershipRelation();
      case DslPackage.SUB_COLLECTION_RELATION: return createSubCollectionRelation();
      case DslPackage.SUB_QUANTITY_RELATION: return createSubQuantityRelation();
      case DslPackage.KIND: return createKind();
      case DslPackage.QUANTITY_UNIVERSAL: return createQuantityUniversal();
      case DslPackage.COLLECTIVE_UNIVERSAL: return createCollectiveUniversal();
      case DslPackage.SUB_KIND: return createSubKind();
      case DslPackage.ROLE: return createRole();
      case DslPackage.PHASE: return createPhase();
      case DslPackage.CATEGORY: return createCategory();
      case DslPackage.MIXIN: return createMixin();
      case DslPackage.ROLE_MIXIN: return createRoleMixin();
      case DslPackage.RELATOR_UNIVERSAL: return createRelatorUniversal();
      case DslPackage.BINARY_MATERIAL_RELATION: return createBinaryMaterialRelation();
      case DslPackage.BINARY_FORMAL_RELATION: return createBinaryFormalRelation();
      case DslPackage.MODE_UNIVERSAL: return createModeUniversal();
      case DslPackage.QUALITY_UNIVERSAL: return createQualityUniversal();
      case DslPackage.NARY_MATERIAL_RELATION: return createnAryMaterialRelation();
      case DslPackage.NARY_FORMAL_RELATION: return createnAryFormalRelation();
      case DslPackage.CHARACTERIZATION: return createCharacterization();
      case DslPackage.MEDIATION: return createMediation();
      case DslPackage.PRIMITIVE_DATA_TYPE_TYPE: return createPrimitiveDataTypeType();
      case DslPackage.DATA_TYPE_ATTRIBUTE: return createDataTypeAttribute();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Model createModel()
  {
    ModelImpl model = new ModelImpl();
    return model;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public PackageableElement createPackageableElement()
  {
    PackageableElementImpl packageableElement = new PackageableElementImpl();
    return packageableElement;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EndurantUniversal createEndurantUniversal()
  {
    EndurantUniversalImpl endurantUniversal = new EndurantUniversalImpl();
    return endurantUniversal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Universal createUniversal()
  {
    UniversalImpl universal = new UniversalImpl();
    return universal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public DataType createDataType()
  {
    DataTypeImpl dataType = new DataTypeImpl();
    return dataType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public IntrinsicMomentUniversal createIntrinsicMomentUniversal()
  {
    IntrinsicMomentUniversalImpl intrinsicMomentUniversal = new IntrinsicMomentUniversalImpl();
    return intrinsicMomentUniversal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ExternallyDependentUniversal createExternallyDependentUniversal()
  {
    ExternallyDependentUniversalImpl externallyDependentUniversal = new ExternallyDependentUniversalImpl();
    return externallyDependentUniversal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public br.ufes.inf.ontouml.ontoumlprime.dsl.Package createPackage()
  {
    PackageImpl package_ = new PackageImpl();
    return package_;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public GeneralizationSet createGeneralizationSet()
  {
    GeneralizationSetImpl generalizationSet = new GeneralizationSetImpl();
    return generalizationSet;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public PrimitiveDataType createPrimitiveDataType()
  {
    PrimitiveDataTypeImpl primitiveDataType = new PrimitiveDataTypeImpl();
    return primitiveDataType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ComplexDataType createComplexDataType()
  {
    ComplexDataTypeImpl complexDataType = new ComplexDataTypeImpl();
    return complexDataType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Enumeration createEnumeration()
  {
    EnumerationImpl enumeration = new EnumerationImpl();
    return enumeration;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public SubstantialUniversal createSubstantialUniversal()
  {
    SubstantialUniversalImpl substantialUniversal = new SubstantialUniversalImpl();
    return substantialUniversal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public MeronymicRelation createMeronymicRelation()
  {
    MeronymicRelationImpl meronymicRelation = new MeronymicRelationImpl();
    return meronymicRelation;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ComponentOfRelation createComponentOfRelation()
  {
    ComponentOfRelationImpl componentOfRelation = new ComponentOfRelationImpl();
    return componentOfRelation;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public MembershipRelation createMembershipRelation()
  {
    MembershipRelationImpl membershipRelation = new MembershipRelationImpl();
    return membershipRelation;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public SubCollectionRelation createSubCollectionRelation()
  {
    SubCollectionRelationImpl subCollectionRelation = new SubCollectionRelationImpl();
    return subCollectionRelation;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public SubQuantityRelation createSubQuantityRelation()
  {
    SubQuantityRelationImpl subQuantityRelation = new SubQuantityRelationImpl();
    return subQuantityRelation;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Kind createKind()
  {
    KindImpl kind = new KindImpl();
    return kind;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public QuantityUniversal createQuantityUniversal()
  {
    QuantityUniversalImpl quantityUniversal = new QuantityUniversalImpl();
    return quantityUniversal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public CollectiveUniversal createCollectiveUniversal()
  {
    CollectiveUniversalImpl collectiveUniversal = new CollectiveUniversalImpl();
    return collectiveUniversal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public SubKind createSubKind()
  {
    SubKindImpl subKind = new SubKindImpl();
    return subKind;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Role createRole()
  {
    RoleImpl role = new RoleImpl();
    return role;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Phase createPhase()
  {
    PhaseImpl phase = new PhaseImpl();
    return phase;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Category createCategory()
  {
    CategoryImpl category = new CategoryImpl();
    return category;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Mixin createMixin()
  {
    MixinImpl mixin = new MixinImpl();
    return mixin;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public RoleMixin createRoleMixin()
  {
    RoleMixinImpl roleMixin = new RoleMixinImpl();
    return roleMixin;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public RelatorUniversal createRelatorUniversal()
  {
    RelatorUniversalImpl relatorUniversal = new RelatorUniversalImpl();
    return relatorUniversal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public BinaryMaterialRelation createBinaryMaterialRelation()
  {
    BinaryMaterialRelationImpl binaryMaterialRelation = new BinaryMaterialRelationImpl();
    return binaryMaterialRelation;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public BinaryFormalRelation createBinaryFormalRelation()
  {
    BinaryFormalRelationImpl binaryFormalRelation = new BinaryFormalRelationImpl();
    return binaryFormalRelation;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ModeUniversal createModeUniversal()
  {
    ModeUniversalImpl modeUniversal = new ModeUniversalImpl();
    return modeUniversal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public QualityUniversal createQualityUniversal()
  {
    QualityUniversalImpl qualityUniversal = new QualityUniversalImpl();
    return qualityUniversal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public nAryMaterialRelation createnAryMaterialRelation()
  {
    nAryMaterialRelationImpl nAryMaterialRelation = new nAryMaterialRelationImpl();
    return nAryMaterialRelation;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public nAryFormalRelation createnAryFormalRelation()
  {
    nAryFormalRelationImpl nAryFormalRelation = new nAryFormalRelationImpl();
    return nAryFormalRelation;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Characterization createCharacterization()
  {
    CharacterizationImpl characterization = new CharacterizationImpl();
    return characterization;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Mediation createMediation()
  {
    MediationImpl mediation = new MediationImpl();
    return mediation;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public PrimitiveDataTypeType createPrimitiveDataTypeType()
  {
    PrimitiveDataTypeTypeImpl primitiveDataTypeType = new PrimitiveDataTypeTypeImpl();
    return primitiveDataTypeType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public DataTypeAttribute createDataTypeAttribute()
  {
    DataTypeAttributeImpl dataTypeAttribute = new DataTypeAttributeImpl();
    return dataTypeAttribute;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public DslPackage getDslPackage()
  {
    return (DslPackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static DslPackage getPackage()
  {
    return DslPackage.eINSTANCE;
  }

} //DslFactoryImpl
