/**
 * generated by Xtext 2.20.0
 */
package br.ufes.inf.ontouml.ontoumlprime.dsl.impl;

import br.ufes.inf.ontouml.ontoumlprime.dsl.BinaryFormalRelation;
import br.ufes.inf.ontouml.ontoumlprime.dsl.BinaryMaterialRelation;
import br.ufes.inf.ontouml.ontoumlprime.dsl.Category;
import br.ufes.inf.ontouml.ontoumlprime.dsl.Characterization;
import br.ufes.inf.ontouml.ontoumlprime.dsl.CollectiveUniversal;
import br.ufes.inf.ontouml.ontoumlprime.dsl.ComplexDataType;
import br.ufes.inf.ontouml.ontoumlprime.dsl.ComponentOfRelation;
import br.ufes.inf.ontouml.ontoumlprime.dsl.DataType;
import br.ufes.inf.ontouml.ontoumlprime.dsl.DataTypeAttribute;
import br.ufes.inf.ontouml.ontoumlprime.dsl.DslFactory;
import br.ufes.inf.ontouml.ontoumlprime.dsl.DslPackage;
import br.ufes.inf.ontouml.ontoumlprime.dsl.EndurantUniversal;
import br.ufes.inf.ontouml.ontoumlprime.dsl.Enumeration;
import br.ufes.inf.ontouml.ontoumlprime.dsl.ExternallyDependentUniversal;
import br.ufes.inf.ontouml.ontoumlprime.dsl.GeneralizationSet;
import br.ufes.inf.ontouml.ontoumlprime.dsl.IntrinsicMomentUniversal;
import br.ufes.inf.ontouml.ontoumlprime.dsl.Kind;
import br.ufes.inf.ontouml.ontoumlprime.dsl.Mediation;
import br.ufes.inf.ontouml.ontoumlprime.dsl.MembershipRelation;
import br.ufes.inf.ontouml.ontoumlprime.dsl.MeronymicRelation;
import br.ufes.inf.ontouml.ontoumlprime.dsl.Mixin;
import br.ufes.inf.ontouml.ontoumlprime.dsl.ModeUniversal;
import br.ufes.inf.ontouml.ontoumlprime.dsl.Model;
import br.ufes.inf.ontouml.ontoumlprime.dsl.PackageableElement;
import br.ufes.inf.ontouml.ontoumlprime.dsl.Phase;
import br.ufes.inf.ontouml.ontoumlprime.dsl.PrimitiveDataType;
import br.ufes.inf.ontouml.ontoumlprime.dsl.PrimitiveDataTypeType;
import br.ufes.inf.ontouml.ontoumlprime.dsl.QualityUniversal;
import br.ufes.inf.ontouml.ontoumlprime.dsl.QuantityUniversal;
import br.ufes.inf.ontouml.ontoumlprime.dsl.RelatorUniversal;
import br.ufes.inf.ontouml.ontoumlprime.dsl.Role;
import br.ufes.inf.ontouml.ontoumlprime.dsl.RoleMixin;
import br.ufes.inf.ontouml.ontoumlprime.dsl.SubCollectionRelation;
import br.ufes.inf.ontouml.ontoumlprime.dsl.SubKind;
import br.ufes.inf.ontouml.ontoumlprime.dsl.SubQuantityRelation;
import br.ufes.inf.ontouml.ontoumlprime.dsl.SubstantialUniversal;
import br.ufes.inf.ontouml.ontoumlprime.dsl.Universal;
import br.ufes.inf.ontouml.ontoumlprime.dsl.nAryFormalRelation;
import br.ufes.inf.ontouml.ontoumlprime.dsl.nAryMaterialRelation;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

import org.eclipse.emf.ecore.impl.EPackageImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Package</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class DslPackageImpl extends EPackageImpl implements DslPackage
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass modelEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass packageableElementEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass endurantUniversalEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass universalEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass dataTypeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass intrinsicMomentUniversalEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass externallyDependentUniversalEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass packageEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass generalizationSetEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass primitiveDataTypeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass complexDataTypeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass enumerationEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass substantialUniversalEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass meronymicRelationEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass componentOfRelationEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass membershipRelationEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass subCollectionRelationEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass subQuantityRelationEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass kindEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass quantityUniversalEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass collectiveUniversalEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass subKindEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass roleEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass phaseEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass categoryEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass mixinEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass roleMixinEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass relatorUniversalEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass binaryMaterialRelationEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass binaryFormalRelationEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass modeUniversalEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass qualityUniversalEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass nAryMaterialRelationEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass nAryFormalRelationEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass characterizationEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass mediationEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass primitiveDataTypeTypeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass dataTypeAttributeEClass = null;

  /**
   * Creates an instance of the model <b>Package</b>, registered with
   * {@link org.eclipse.emf.ecore.EPackage.Registry EPackage.Registry} by the package
   * package URI value.
   * <p>Note: the correct way to create the package is via the static
   * factory method {@link #init init()}, which also performs
   * initialization of the package, or returns the registered package,
   * if one already exists.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.emf.ecore.EPackage.Registry
   * @see br.ufes.inf.ontouml.ontoumlprime.dsl.DslPackage#eNS_URI
   * @see #init()
   * @generated
   */
  private DslPackageImpl()
  {
    super(eNS_URI, DslFactory.eINSTANCE);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static boolean isInited = false;

  /**
   * Creates, registers, and initializes the <b>Package</b> for this model, and for any others upon which it depends.
   * 
   * <p>This method is used to initialize {@link DslPackage#eINSTANCE} when that field is accessed.
   * Clients should not invoke it directly. Instead, they should simply access that field to obtain the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #eNS_URI
   * @see #createPackageContents()
   * @see #initializePackageContents()
   * @generated
   */
  public static DslPackage init()
  {
    if (isInited) return (DslPackage)EPackage.Registry.INSTANCE.getEPackage(DslPackage.eNS_URI);

    // Obtain or create and register package
    DslPackageImpl theDslPackage = (DslPackageImpl)(EPackage.Registry.INSTANCE.get(eNS_URI) instanceof DslPackageImpl ? EPackage.Registry.INSTANCE.get(eNS_URI) : new DslPackageImpl());

    isInited = true;

    // Create package meta-data objects
    theDslPackage.createPackageContents();

    // Initialize created meta-data
    theDslPackage.initializePackageContents();

    // Mark meta-data to indicate it can't be changed
    theDslPackage.freeze();

  
    // Update the registry and return the package
    EPackage.Registry.INSTANCE.put(DslPackage.eNS_URI, theDslPackage);
    return theDslPackage;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getModel()
  {
    return modelEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getModel_Elements()
  {
    return (EReference)modelEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getPackageableElement()
  {
    return packageableElementEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getEndurantUniversal()
  {
    return endurantUniversalEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getUniversal()
  {
    return universalEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getDataType()
  {
    return dataTypeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getIntrinsicMomentUniversal()
  {
    return intrinsicMomentUniversalEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getExternallyDependentUniversal()
  {
    return externallyDependentUniversalEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getPackage()
  {
    return packageEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getPackage_Name()
  {
    return (EAttribute)packageEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getPackage_Elements()
  {
    return (EReference)packageEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getGeneralizationSet()
  {
    return generalizationSetEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getGeneralizationSet_IsCovering()
  {
    return (EAttribute)generalizationSetEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getGeneralizationSet_Name()
  {
    return (EAttribute)generalizationSetEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getGeneralizationSet_SpecializedUniversal()
  {
    return (EReference)generalizationSetEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getGeneralizationSet_SpecializingUniversals()
  {
    return (EReference)generalizationSetEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getPrimitiveDataType()
  {
    return primitiveDataTypeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getPrimitiveDataType_Name()
  {
    return (EAttribute)primitiveDataTypeEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getPrimitiveDataType__type()
  {
    return (EReference)primitiveDataTypeEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getComplexDataType()
  {
    return complexDataTypeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getComplexDataType_Name()
  {
    return (EAttribute)complexDataTypeEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getComplexDataType_Attributes()
  {
    return (EReference)complexDataTypeEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getEnumeration()
  {
    return enumerationEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getEnumeration_Name()
  {
    return (EAttribute)enumerationEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getEnumeration_EnumerationLiterals()
  {
    return (EAttribute)enumerationEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getSubstantialUniversal()
  {
    return substantialUniversalEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getMeronymicRelation()
  {
    return meronymicRelationEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getMeronymicRelation_PartIsEssential()
  {
    return (EAttribute)meronymicRelationEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getMeronymicRelation_PartIsInseparable()
  {
    return (EAttribute)meronymicRelationEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getMeronymicRelation_PartIsImmutable()
  {
    return (EAttribute)meronymicRelationEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getMeronymicRelation_Part()
  {
    return (EReference)meronymicRelationEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getMeronymicRelation_SourceLowerBound()
  {
    return (EAttribute)meronymicRelationEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getMeronymicRelation_SourceUpperBound()
  {
    return (EAttribute)meronymicRelationEClass.getEStructuralFeatures().get(5);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getMeronymicRelation_Whole()
  {
    return (EReference)meronymicRelationEClass.getEStructuralFeatures().get(6);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getMeronymicRelation_TargetLowerBound()
  {
    return (EAttribute)meronymicRelationEClass.getEStructuralFeatures().get(7);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getMeronymicRelation_TargetUpperBound()
  {
    return (EAttribute)meronymicRelationEClass.getEStructuralFeatures().get(8);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getComponentOfRelation()
  {
    return componentOfRelationEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getComponentOfRelation_PartIsShareable()
  {
    return (EAttribute)componentOfRelationEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getMembershipRelation()
  {
    return membershipRelationEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getMembershipRelation_PartIsShareable()
  {
    return (EAttribute)membershipRelationEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getSubCollectionRelation()
  {
    return subCollectionRelationEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getSubCollectionRelation_PartIsShareable()
  {
    return (EAttribute)subCollectionRelationEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getSubQuantityRelation()
  {
    return subQuantityRelationEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getKind()
  {
    return kindEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getKind_Name()
  {
    return (EAttribute)kindEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getKind_CharacterizedBy()
  {
    return (EReference)kindEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getQuantityUniversal()
  {
    return quantityUniversalEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getQuantityUniversal_Name()
  {
    return (EAttribute)quantityUniversalEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getQuantityUniversal_CharacterizedBy()
  {
    return (EReference)quantityUniversalEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getCollectiveUniversal()
  {
    return collectiveUniversalEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getCollectiveUniversal_IsExtensional()
  {
    return (EAttribute)collectiveUniversalEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getCollectiveUniversal_Name()
  {
    return (EAttribute)collectiveUniversalEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getCollectiveUniversal_CharacterizedBy()
  {
    return (EReference)collectiveUniversalEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getSubKind()
  {
    return subKindEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getSubKind_Name()
  {
    return (EAttribute)subKindEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getSubKind_CharacterizedBy()
  {
    return (EReference)subKindEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getRole()
  {
    return roleEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getRole_Name()
  {
    return (EAttribute)roleEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getRole_CharacterizedBy()
  {
    return (EReference)roleEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getPhase()
  {
    return phaseEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getPhase_Name()
  {
    return (EAttribute)phaseEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getPhase_CharacterizedBy()
  {
    return (EReference)phaseEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getCategory()
  {
    return categoryEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getCategory_Name()
  {
    return (EAttribute)categoryEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getMixin()
  {
    return mixinEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getMixin_Name()
  {
    return (EAttribute)mixinEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getRoleMixin()
  {
    return roleMixinEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getRoleMixin_Name()
  {
    return (EAttribute)roleMixinEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getRelatorUniversal()
  {
    return relatorUniversalEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getRelatorUniversal_Name()
  {
    return (EAttribute)relatorUniversalEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getRelatorUniversal_CharacterizedBy()
  {
    return (EReference)relatorUniversalEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getRelatorUniversal_Mediations()
  {
    return (EReference)relatorUniversalEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getBinaryMaterialRelation()
  {
    return binaryMaterialRelationEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getBinaryMaterialRelation_Source()
  {
    return (EReference)binaryMaterialRelationEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getBinaryMaterialRelation_SourceLowerBound()
  {
    return (EAttribute)binaryMaterialRelationEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getBinaryMaterialRelation_SourceUpperBound()
  {
    return (EAttribute)binaryMaterialRelationEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getBinaryMaterialRelation_Name()
  {
    return (EAttribute)binaryMaterialRelationEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getBinaryMaterialRelation_DerivedFrom()
  {
    return (EReference)binaryMaterialRelationEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getBinaryMaterialRelation_Target()
  {
    return (EReference)binaryMaterialRelationEClass.getEStructuralFeatures().get(5);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getBinaryMaterialRelation_TargetLowerBound()
  {
    return (EAttribute)binaryMaterialRelationEClass.getEStructuralFeatures().get(6);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getBinaryMaterialRelation_TargetUpperBound()
  {
    return (EAttribute)binaryMaterialRelationEClass.getEStructuralFeatures().get(7);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getBinaryFormalRelation()
  {
    return binaryFormalRelationEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getBinaryFormalRelation_Source()
  {
    return (EReference)binaryFormalRelationEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getBinaryFormalRelation_SourceLowerBound()
  {
    return (EAttribute)binaryFormalRelationEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getBinaryFormalRelation_SourceUpperBound()
  {
    return (EAttribute)binaryFormalRelationEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getBinaryFormalRelation_Name()
  {
    return (EAttribute)binaryFormalRelationEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getBinaryFormalRelation_Target()
  {
    return (EReference)binaryFormalRelationEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getBinaryFormalRelation_TargetLowerBound()
  {
    return (EAttribute)binaryFormalRelationEClass.getEStructuralFeatures().get(5);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getBinaryFormalRelation_TargetUpperBound()
  {
    return (EAttribute)binaryFormalRelationEClass.getEStructuralFeatures().get(6);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getModeUniversal()
  {
    return modeUniversalEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getModeUniversal_Name()
  {
    return (EAttribute)modeUniversalEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getModeUniversal_CharacterizedBy()
  {
    return (EReference)modeUniversalEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getQualityUniversal()
  {
    return qualityUniversalEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getQualityUniversal_Name()
  {
    return (EAttribute)qualityUniversalEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getQualityUniversal_Characterization()
  {
    return (EReference)qualityUniversalEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getQualityUniversal_Datatypes()
  {
    return (EReference)qualityUniversalEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getQualityUniversal_CharacterizedBy()
  {
    return (EReference)qualityUniversalEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getnAryMaterialRelation()
  {
    return nAryMaterialRelationEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getnAryMaterialRelation_DerivedFrom()
  {
    return (EReference)nAryMaterialRelationEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getnAryMaterialRelation_Name()
  {
    return (EAttribute)nAryMaterialRelationEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getnAryMaterialRelation_TargetRelata()
  {
    return (EReference)nAryMaterialRelationEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getnAryMaterialRelation_SourceLowerBound()
  {
    return (EAttribute)nAryMaterialRelationEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getnAryMaterialRelation_SourceUpperBound()
  {
    return (EAttribute)nAryMaterialRelationEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getnAryFormalRelation()
  {
    return nAryFormalRelationEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getnAryFormalRelation_Name()
  {
    return (EAttribute)nAryFormalRelationEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getnAryFormalRelation_TargetRelata()
  {
    return (EReference)nAryFormalRelationEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getnAryFormalRelation_SourceLowerBound()
  {
    return (EAttribute)nAryFormalRelationEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getnAryFormalRelation_SourceUpperBound()
  {
    return (EAttribute)nAryFormalRelationEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getCharacterization()
  {
    return characterizationEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getCharacterization_SourceLowerBound()
  {
    return (EAttribute)characterizationEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getCharacterization_SourceUpperBound()
  {
    return (EAttribute)characterizationEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getCharacterization_Target()
  {
    return (EReference)characterizationEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getCharacterization_TargetLowerBound()
  {
    return (EAttribute)characterizationEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getCharacterization_TargetUpperBound()
  {
    return (EAttribute)characterizationEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getMediation()
  {
    return mediationEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getMediation_SourceLowerBound()
  {
    return (EAttribute)mediationEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getMediation_SourceUpperBound()
  {
    return (EAttribute)mediationEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getMediation_Target()
  {
    return (EReference)mediationEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getMediation_TargetLowerBound()
  {
    return (EAttribute)mediationEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getMediation_TargetUpperBound()
  {
    return (EAttribute)mediationEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getPrimitiveDataTypeType()
  {
    return primitiveDataTypeTypeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getDataTypeAttribute()
  {
    return dataTypeAttributeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getDataTypeAttribute_IsOfType()
  {
    return (EReference)dataTypeAttributeEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getDataTypeAttribute_Name()
  {
    return (EAttribute)dataTypeAttributeEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public DslFactory getDslFactory()
  {
    return (DslFactory)getEFactoryInstance();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isCreated = false;

  /**
   * Creates the meta-model objects for the package.  This method is
   * guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void createPackageContents()
  {
    if (isCreated) return;
    isCreated = true;

    // Create classes and their features
    modelEClass = createEClass(MODEL);
    createEReference(modelEClass, MODEL__ELEMENTS);

    packageableElementEClass = createEClass(PACKAGEABLE_ELEMENT);

    endurantUniversalEClass = createEClass(ENDURANT_UNIVERSAL);

    universalEClass = createEClass(UNIVERSAL);

    dataTypeEClass = createEClass(DATA_TYPE);

    intrinsicMomentUniversalEClass = createEClass(INTRINSIC_MOMENT_UNIVERSAL);

    externallyDependentUniversalEClass = createEClass(EXTERNALLY_DEPENDENT_UNIVERSAL);

    packageEClass = createEClass(PACKAGE);
    createEAttribute(packageEClass, PACKAGE__NAME);
    createEReference(packageEClass, PACKAGE__ELEMENTS);

    generalizationSetEClass = createEClass(GENERALIZATION_SET);
    createEAttribute(generalizationSetEClass, GENERALIZATION_SET__IS_COVERING);
    createEAttribute(generalizationSetEClass, GENERALIZATION_SET__NAME);
    createEReference(generalizationSetEClass, GENERALIZATION_SET__SPECIALIZED_UNIVERSAL);
    createEReference(generalizationSetEClass, GENERALIZATION_SET__SPECIALIZING_UNIVERSALS);

    primitiveDataTypeEClass = createEClass(PRIMITIVE_DATA_TYPE);
    createEAttribute(primitiveDataTypeEClass, PRIMITIVE_DATA_TYPE__NAME);
    createEReference(primitiveDataTypeEClass, PRIMITIVE_DATA_TYPE__TYPE);

    complexDataTypeEClass = createEClass(COMPLEX_DATA_TYPE);
    createEAttribute(complexDataTypeEClass, COMPLEX_DATA_TYPE__NAME);
    createEReference(complexDataTypeEClass, COMPLEX_DATA_TYPE__ATTRIBUTES);

    enumerationEClass = createEClass(ENUMERATION);
    createEAttribute(enumerationEClass, ENUMERATION__NAME);
    createEAttribute(enumerationEClass, ENUMERATION__ENUMERATION_LITERALS);

    substantialUniversalEClass = createEClass(SUBSTANTIAL_UNIVERSAL);

    meronymicRelationEClass = createEClass(MERONYMIC_RELATION);
    createEAttribute(meronymicRelationEClass, MERONYMIC_RELATION__PART_IS_ESSENTIAL);
    createEAttribute(meronymicRelationEClass, MERONYMIC_RELATION__PART_IS_INSEPARABLE);
    createEAttribute(meronymicRelationEClass, MERONYMIC_RELATION__PART_IS_IMMUTABLE);
    createEReference(meronymicRelationEClass, MERONYMIC_RELATION__PART);
    createEAttribute(meronymicRelationEClass, MERONYMIC_RELATION__SOURCE_LOWER_BOUND);
    createEAttribute(meronymicRelationEClass, MERONYMIC_RELATION__SOURCE_UPPER_BOUND);
    createEReference(meronymicRelationEClass, MERONYMIC_RELATION__WHOLE);
    createEAttribute(meronymicRelationEClass, MERONYMIC_RELATION__TARGET_LOWER_BOUND);
    createEAttribute(meronymicRelationEClass, MERONYMIC_RELATION__TARGET_UPPER_BOUND);

    componentOfRelationEClass = createEClass(COMPONENT_OF_RELATION);
    createEAttribute(componentOfRelationEClass, COMPONENT_OF_RELATION__PART_IS_SHAREABLE);

    membershipRelationEClass = createEClass(MEMBERSHIP_RELATION);
    createEAttribute(membershipRelationEClass, MEMBERSHIP_RELATION__PART_IS_SHAREABLE);

    subCollectionRelationEClass = createEClass(SUB_COLLECTION_RELATION);
    createEAttribute(subCollectionRelationEClass, SUB_COLLECTION_RELATION__PART_IS_SHAREABLE);

    subQuantityRelationEClass = createEClass(SUB_QUANTITY_RELATION);

    kindEClass = createEClass(KIND);
    createEAttribute(kindEClass, KIND__NAME);
    createEReference(kindEClass, KIND__CHARACTERIZED_BY);

    quantityUniversalEClass = createEClass(QUANTITY_UNIVERSAL);
    createEAttribute(quantityUniversalEClass, QUANTITY_UNIVERSAL__NAME);
    createEReference(quantityUniversalEClass, QUANTITY_UNIVERSAL__CHARACTERIZED_BY);

    collectiveUniversalEClass = createEClass(COLLECTIVE_UNIVERSAL);
    createEAttribute(collectiveUniversalEClass, COLLECTIVE_UNIVERSAL__IS_EXTENSIONAL);
    createEAttribute(collectiveUniversalEClass, COLLECTIVE_UNIVERSAL__NAME);
    createEReference(collectiveUniversalEClass, COLLECTIVE_UNIVERSAL__CHARACTERIZED_BY);

    subKindEClass = createEClass(SUB_KIND);
    createEAttribute(subKindEClass, SUB_KIND__NAME);
    createEReference(subKindEClass, SUB_KIND__CHARACTERIZED_BY);

    roleEClass = createEClass(ROLE);
    createEAttribute(roleEClass, ROLE__NAME);
    createEReference(roleEClass, ROLE__CHARACTERIZED_BY);

    phaseEClass = createEClass(PHASE);
    createEAttribute(phaseEClass, PHASE__NAME);
    createEReference(phaseEClass, PHASE__CHARACTERIZED_BY);

    categoryEClass = createEClass(CATEGORY);
    createEAttribute(categoryEClass, CATEGORY__NAME);

    mixinEClass = createEClass(MIXIN);
    createEAttribute(mixinEClass, MIXIN__NAME);

    roleMixinEClass = createEClass(ROLE_MIXIN);
    createEAttribute(roleMixinEClass, ROLE_MIXIN__NAME);

    relatorUniversalEClass = createEClass(RELATOR_UNIVERSAL);
    createEAttribute(relatorUniversalEClass, RELATOR_UNIVERSAL__NAME);
    createEReference(relatorUniversalEClass, RELATOR_UNIVERSAL__CHARACTERIZED_BY);
    createEReference(relatorUniversalEClass, RELATOR_UNIVERSAL__MEDIATIONS);

    binaryMaterialRelationEClass = createEClass(BINARY_MATERIAL_RELATION);
    createEReference(binaryMaterialRelationEClass, BINARY_MATERIAL_RELATION__SOURCE);
    createEAttribute(binaryMaterialRelationEClass, BINARY_MATERIAL_RELATION__SOURCE_LOWER_BOUND);
    createEAttribute(binaryMaterialRelationEClass, BINARY_MATERIAL_RELATION__SOURCE_UPPER_BOUND);
    createEAttribute(binaryMaterialRelationEClass, BINARY_MATERIAL_RELATION__NAME);
    createEReference(binaryMaterialRelationEClass, BINARY_MATERIAL_RELATION__DERIVED_FROM);
    createEReference(binaryMaterialRelationEClass, BINARY_MATERIAL_RELATION__TARGET);
    createEAttribute(binaryMaterialRelationEClass, BINARY_MATERIAL_RELATION__TARGET_LOWER_BOUND);
    createEAttribute(binaryMaterialRelationEClass, BINARY_MATERIAL_RELATION__TARGET_UPPER_BOUND);

    binaryFormalRelationEClass = createEClass(BINARY_FORMAL_RELATION);
    createEReference(binaryFormalRelationEClass, BINARY_FORMAL_RELATION__SOURCE);
    createEAttribute(binaryFormalRelationEClass, BINARY_FORMAL_RELATION__SOURCE_LOWER_BOUND);
    createEAttribute(binaryFormalRelationEClass, BINARY_FORMAL_RELATION__SOURCE_UPPER_BOUND);
    createEAttribute(binaryFormalRelationEClass, BINARY_FORMAL_RELATION__NAME);
    createEReference(binaryFormalRelationEClass, BINARY_FORMAL_RELATION__TARGET);
    createEAttribute(binaryFormalRelationEClass, BINARY_FORMAL_RELATION__TARGET_LOWER_BOUND);
    createEAttribute(binaryFormalRelationEClass, BINARY_FORMAL_RELATION__TARGET_UPPER_BOUND);

    modeUniversalEClass = createEClass(MODE_UNIVERSAL);
    createEAttribute(modeUniversalEClass, MODE_UNIVERSAL__NAME);
    createEReference(modeUniversalEClass, MODE_UNIVERSAL__CHARACTERIZED_BY);

    qualityUniversalEClass = createEClass(QUALITY_UNIVERSAL);
    createEAttribute(qualityUniversalEClass, QUALITY_UNIVERSAL__NAME);
    createEReference(qualityUniversalEClass, QUALITY_UNIVERSAL__CHARACTERIZATION);
    createEReference(qualityUniversalEClass, QUALITY_UNIVERSAL__DATATYPES);
    createEReference(qualityUniversalEClass, QUALITY_UNIVERSAL__CHARACTERIZED_BY);

    nAryMaterialRelationEClass = createEClass(NARY_MATERIAL_RELATION);
    createEReference(nAryMaterialRelationEClass, NARY_MATERIAL_RELATION__DERIVED_FROM);
    createEAttribute(nAryMaterialRelationEClass, NARY_MATERIAL_RELATION__NAME);
    createEReference(nAryMaterialRelationEClass, NARY_MATERIAL_RELATION__TARGET_RELATA);
    createEAttribute(nAryMaterialRelationEClass, NARY_MATERIAL_RELATION__SOURCE_LOWER_BOUND);
    createEAttribute(nAryMaterialRelationEClass, NARY_MATERIAL_RELATION__SOURCE_UPPER_BOUND);

    nAryFormalRelationEClass = createEClass(NARY_FORMAL_RELATION);
    createEAttribute(nAryFormalRelationEClass, NARY_FORMAL_RELATION__NAME);
    createEReference(nAryFormalRelationEClass, NARY_FORMAL_RELATION__TARGET_RELATA);
    createEAttribute(nAryFormalRelationEClass, NARY_FORMAL_RELATION__SOURCE_LOWER_BOUND);
    createEAttribute(nAryFormalRelationEClass, NARY_FORMAL_RELATION__SOURCE_UPPER_BOUND);

    characterizationEClass = createEClass(CHARACTERIZATION);
    createEAttribute(characterizationEClass, CHARACTERIZATION__SOURCE_LOWER_BOUND);
    createEAttribute(characterizationEClass, CHARACTERIZATION__SOURCE_UPPER_BOUND);
    createEReference(characterizationEClass, CHARACTERIZATION__TARGET);
    createEAttribute(characterizationEClass, CHARACTERIZATION__TARGET_LOWER_BOUND);
    createEAttribute(characterizationEClass, CHARACTERIZATION__TARGET_UPPER_BOUND);

    mediationEClass = createEClass(MEDIATION);
    createEAttribute(mediationEClass, MEDIATION__SOURCE_LOWER_BOUND);
    createEAttribute(mediationEClass, MEDIATION__SOURCE_UPPER_BOUND);
    createEReference(mediationEClass, MEDIATION__TARGET);
    createEAttribute(mediationEClass, MEDIATION__TARGET_LOWER_BOUND);
    createEAttribute(mediationEClass, MEDIATION__TARGET_UPPER_BOUND);

    primitiveDataTypeTypeEClass = createEClass(PRIMITIVE_DATA_TYPE_TYPE);

    dataTypeAttributeEClass = createEClass(DATA_TYPE_ATTRIBUTE);
    createEReference(dataTypeAttributeEClass, DATA_TYPE_ATTRIBUTE__IS_OF_TYPE);
    createEAttribute(dataTypeAttributeEClass, DATA_TYPE_ATTRIBUTE__NAME);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isInitialized = false;

  /**
   * Complete the initialization of the package and its meta-model.  This
   * method is guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void initializePackageContents()
  {
    if (isInitialized) return;
    isInitialized = true;

    // Initialize package
    setName(eNAME);
    setNsPrefix(eNS_PREFIX);
    setNsURI(eNS_URI);

    // Create type parameters

    // Set bounds for type parameters

    // Add supertypes to classes
    packageEClass.getESuperTypes().add(this.getPackageableElement());
    generalizationSetEClass.getESuperTypes().add(this.getPackageableElement());
    primitiveDataTypeEClass.getESuperTypes().add(this.getPackageableElement());
    primitiveDataTypeEClass.getESuperTypes().add(this.getDataType());
    complexDataTypeEClass.getESuperTypes().add(this.getPackageableElement());
    complexDataTypeEClass.getESuperTypes().add(this.getDataType());
    enumerationEClass.getESuperTypes().add(this.getPackageableElement());
    enumerationEClass.getESuperTypes().add(this.getDataType());
    meronymicRelationEClass.getESuperTypes().add(this.getPackageableElement());
    componentOfRelationEClass.getESuperTypes().add(this.getMeronymicRelation());
    membershipRelationEClass.getESuperTypes().add(this.getMeronymicRelation());
    subCollectionRelationEClass.getESuperTypes().add(this.getMeronymicRelation());
    subQuantityRelationEClass.getESuperTypes().add(this.getMeronymicRelation());
    kindEClass.getESuperTypes().add(this.getPackageableElement());
    kindEClass.getESuperTypes().add(this.getEndurantUniversal());
    kindEClass.getESuperTypes().add(this.getUniversal());
    kindEClass.getESuperTypes().add(this.getSubstantialUniversal());
    quantityUniversalEClass.getESuperTypes().add(this.getPackageableElement());
    quantityUniversalEClass.getESuperTypes().add(this.getEndurantUniversal());
    quantityUniversalEClass.getESuperTypes().add(this.getUniversal());
    quantityUniversalEClass.getESuperTypes().add(this.getSubstantialUniversal());
    collectiveUniversalEClass.getESuperTypes().add(this.getPackageableElement());
    collectiveUniversalEClass.getESuperTypes().add(this.getEndurantUniversal());
    collectiveUniversalEClass.getESuperTypes().add(this.getUniversal());
    collectiveUniversalEClass.getESuperTypes().add(this.getSubstantialUniversal());
    subKindEClass.getESuperTypes().add(this.getPackageableElement());
    subKindEClass.getESuperTypes().add(this.getEndurantUniversal());
    subKindEClass.getESuperTypes().add(this.getUniversal());
    subKindEClass.getESuperTypes().add(this.getSubstantialUniversal());
    roleEClass.getESuperTypes().add(this.getPackageableElement());
    roleEClass.getESuperTypes().add(this.getEndurantUniversal());
    roleEClass.getESuperTypes().add(this.getUniversal());
    roleEClass.getESuperTypes().add(this.getExternallyDependentUniversal());
    roleEClass.getESuperTypes().add(this.getSubstantialUniversal());
    phaseEClass.getESuperTypes().add(this.getPackageableElement());
    phaseEClass.getESuperTypes().add(this.getEndurantUniversal());
    phaseEClass.getESuperTypes().add(this.getUniversal());
    phaseEClass.getESuperTypes().add(this.getSubstantialUniversal());
    categoryEClass.getESuperTypes().add(this.getPackageableElement());
    categoryEClass.getESuperTypes().add(this.getUniversal());
    mixinEClass.getESuperTypes().add(this.getPackageableElement());
    mixinEClass.getESuperTypes().add(this.getUniversal());
    roleMixinEClass.getESuperTypes().add(this.getPackageableElement());
    roleMixinEClass.getESuperTypes().add(this.getUniversal());
    roleMixinEClass.getESuperTypes().add(this.getExternallyDependentUniversal());
    relatorUniversalEClass.getESuperTypes().add(this.getPackageableElement());
    relatorUniversalEClass.getESuperTypes().add(this.getEndurantUniversal());
    relatorUniversalEClass.getESuperTypes().add(this.getUniversal());
    binaryMaterialRelationEClass.getESuperTypes().add(this.getPackageableElement());
    binaryFormalRelationEClass.getESuperTypes().add(this.getPackageableElement());
    modeUniversalEClass.getESuperTypes().add(this.getPackageableElement());
    modeUniversalEClass.getESuperTypes().add(this.getEndurantUniversal());
    modeUniversalEClass.getESuperTypes().add(this.getUniversal());
    modeUniversalEClass.getESuperTypes().add(this.getIntrinsicMomentUniversal());
    qualityUniversalEClass.getESuperTypes().add(this.getPackageableElement());
    qualityUniversalEClass.getESuperTypes().add(this.getEndurantUniversal());
    qualityUniversalEClass.getESuperTypes().add(this.getUniversal());
    qualityUniversalEClass.getESuperTypes().add(this.getIntrinsicMomentUniversal());
    nAryMaterialRelationEClass.getESuperTypes().add(this.getPackageableElement());
    nAryFormalRelationEClass.getESuperTypes().add(this.getPackageableElement());

    // Initialize classes and features; add operations and parameters
    initEClass(modelEClass, Model.class, "Model", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getModel_Elements(), this.getPackageableElement(), null, "elements", null, 0, -1, Model.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(packageableElementEClass, PackageableElement.class, "PackageableElement", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(endurantUniversalEClass, EndurantUniversal.class, "EndurantUniversal", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(universalEClass, Universal.class, "Universal", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(dataTypeEClass, DataType.class, "DataType", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(intrinsicMomentUniversalEClass, IntrinsicMomentUniversal.class, "IntrinsicMomentUniversal", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(externallyDependentUniversalEClass, ExternallyDependentUniversal.class, "ExternallyDependentUniversal", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(packageEClass, br.ufes.inf.ontouml.ontoumlprime.dsl.Package.class, "Package", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getPackage_Name(), ecorePackage.getEString(), "name", null, 0, 1, br.ufes.inf.ontouml.ontoumlprime.dsl.Package.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getPackage_Elements(), this.getPackageableElement(), null, "elements", null, 0, -1, br.ufes.inf.ontouml.ontoumlprime.dsl.Package.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(generalizationSetEClass, GeneralizationSet.class, "GeneralizationSet", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getGeneralizationSet_IsCovering(), ecorePackage.getEBoolean(), "isCovering", null, 0, 1, GeneralizationSet.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getGeneralizationSet_Name(), ecorePackage.getEString(), "name", null, 0, 1, GeneralizationSet.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getGeneralizationSet_SpecializedUniversal(), this.getUniversal(), null, "specializedUniversal", null, 0, 1, GeneralizationSet.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getGeneralizationSet_SpecializingUniversals(), this.getUniversal(), null, "specializingUniversals", null, 0, -1, GeneralizationSet.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(primitiveDataTypeEClass, PrimitiveDataType.class, "PrimitiveDataType", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getPrimitiveDataType_Name(), ecorePackage.getEString(), "name", null, 0, 1, PrimitiveDataType.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getPrimitiveDataType__type(), this.getPrimitiveDataTypeType(), null, "_type", null, 0, 1, PrimitiveDataType.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(complexDataTypeEClass, ComplexDataType.class, "ComplexDataType", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getComplexDataType_Name(), ecorePackage.getEString(), "name", null, 0, 1, ComplexDataType.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getComplexDataType_Attributes(), this.getDataTypeAttribute(), null, "attributes", null, 0, -1, ComplexDataType.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(enumerationEClass, Enumeration.class, "Enumeration", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getEnumeration_Name(), ecorePackage.getEString(), "name", null, 0, 1, Enumeration.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getEnumeration_EnumerationLiterals(), ecorePackage.getEString(), "enumerationLiterals", null, 0, -1, Enumeration.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(substantialUniversalEClass, SubstantialUniversal.class, "SubstantialUniversal", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(meronymicRelationEClass, MeronymicRelation.class, "MeronymicRelation", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getMeronymicRelation_PartIsEssential(), ecorePackage.getEBoolean(), "partIsEssential", null, 0, 1, MeronymicRelation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getMeronymicRelation_PartIsInseparable(), ecorePackage.getEBoolean(), "partIsInseparable", null, 0, 1, MeronymicRelation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getMeronymicRelation_PartIsImmutable(), ecorePackage.getEBoolean(), "partIsImmutable", null, 0, 1, MeronymicRelation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getMeronymicRelation_Part(), this.getSubstantialUniversal(), null, "part", null, 0, 1, MeronymicRelation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getMeronymicRelation_SourceLowerBound(), ecorePackage.getEInt(), "sourceLowerBound", null, 0, 1, MeronymicRelation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getMeronymicRelation_SourceUpperBound(), ecorePackage.getEInt(), "sourceUpperBound", null, 0, 1, MeronymicRelation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getMeronymicRelation_Whole(), this.getSubstantialUniversal(), null, "whole", null, 0, 1, MeronymicRelation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getMeronymicRelation_TargetLowerBound(), ecorePackage.getEInt(), "targetLowerBound", null, 0, 1, MeronymicRelation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getMeronymicRelation_TargetUpperBound(), ecorePackage.getEInt(), "targetUpperBound", null, 0, 1, MeronymicRelation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(componentOfRelationEClass, ComponentOfRelation.class, "ComponentOfRelation", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getComponentOfRelation_PartIsShareable(), ecorePackage.getEBoolean(), "partIsShareable", null, 0, 1, ComponentOfRelation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(membershipRelationEClass, MembershipRelation.class, "MembershipRelation", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getMembershipRelation_PartIsShareable(), ecorePackage.getEBoolean(), "partIsShareable", null, 0, 1, MembershipRelation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(subCollectionRelationEClass, SubCollectionRelation.class, "SubCollectionRelation", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getSubCollectionRelation_PartIsShareable(), ecorePackage.getEBoolean(), "partIsShareable", null, 0, 1, SubCollectionRelation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(subQuantityRelationEClass, SubQuantityRelation.class, "SubQuantityRelation", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(kindEClass, Kind.class, "Kind", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getKind_Name(), ecorePackage.getEString(), "name", null, 0, 1, Kind.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getKind_CharacterizedBy(), this.getCharacterization(), null, "characterizedBy", null, 0, -1, Kind.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(quantityUniversalEClass, QuantityUniversal.class, "QuantityUniversal", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getQuantityUniversal_Name(), ecorePackage.getEString(), "name", null, 0, 1, QuantityUniversal.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getQuantityUniversal_CharacterizedBy(), this.getCharacterization(), null, "characterizedBy", null, 0, -1, QuantityUniversal.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(collectiveUniversalEClass, CollectiveUniversal.class, "CollectiveUniversal", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getCollectiveUniversal_IsExtensional(), ecorePackage.getEBoolean(), "isExtensional", null, 0, 1, CollectiveUniversal.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getCollectiveUniversal_Name(), ecorePackage.getEString(), "name", null, 0, 1, CollectiveUniversal.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getCollectiveUniversal_CharacterizedBy(), this.getCharacterization(), null, "characterizedBy", null, 0, -1, CollectiveUniversal.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(subKindEClass, SubKind.class, "SubKind", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getSubKind_Name(), ecorePackage.getEString(), "name", null, 0, 1, SubKind.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getSubKind_CharacterizedBy(), this.getCharacterization(), null, "characterizedBy", null, 0, -1, SubKind.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(roleEClass, Role.class, "Role", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getRole_Name(), ecorePackage.getEString(), "name", null, 0, 1, Role.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getRole_CharacterizedBy(), this.getCharacterization(), null, "characterizedBy", null, 0, -1, Role.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(phaseEClass, Phase.class, "Phase", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getPhase_Name(), ecorePackage.getEString(), "name", null, 0, 1, Phase.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getPhase_CharacterizedBy(), this.getCharacterization(), null, "characterizedBy", null, 0, -1, Phase.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(categoryEClass, Category.class, "Category", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getCategory_Name(), ecorePackage.getEString(), "name", null, 0, 1, Category.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(mixinEClass, Mixin.class, "Mixin", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getMixin_Name(), ecorePackage.getEString(), "name", null, 0, 1, Mixin.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(roleMixinEClass, RoleMixin.class, "RoleMixin", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getRoleMixin_Name(), ecorePackage.getEString(), "name", null, 0, 1, RoleMixin.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(relatorUniversalEClass, RelatorUniversal.class, "RelatorUniversal", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getRelatorUniversal_Name(), ecorePackage.getEString(), "name", null, 0, 1, RelatorUniversal.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getRelatorUniversal_CharacterizedBy(), this.getCharacterization(), null, "characterizedBy", null, 0, -1, RelatorUniversal.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getRelatorUniversal_Mediations(), this.getMediation(), null, "mediations", null, 0, -1, RelatorUniversal.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(binaryMaterialRelationEClass, BinaryMaterialRelation.class, "BinaryMaterialRelation", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getBinaryMaterialRelation_Source(), this.getExternallyDependentUniversal(), null, "source", null, 0, 1, BinaryMaterialRelation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getBinaryMaterialRelation_SourceLowerBound(), ecorePackage.getEInt(), "sourceLowerBound", null, 0, 1, BinaryMaterialRelation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getBinaryMaterialRelation_SourceUpperBound(), ecorePackage.getEInt(), "sourceUpperBound", null, 0, 1, BinaryMaterialRelation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getBinaryMaterialRelation_Name(), ecorePackage.getEString(), "name", null, 0, 1, BinaryMaterialRelation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getBinaryMaterialRelation_DerivedFrom(), this.getRelatorUniversal(), null, "derivedFrom", null, 0, 1, BinaryMaterialRelation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getBinaryMaterialRelation_Target(), this.getExternallyDependentUniversal(), null, "target", null, 0, 1, BinaryMaterialRelation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getBinaryMaterialRelation_TargetLowerBound(), ecorePackage.getEInt(), "targetLowerBound", null, 0, 1, BinaryMaterialRelation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getBinaryMaterialRelation_TargetUpperBound(), ecorePackage.getEInt(), "targetUpperBound", null, 0, 1, BinaryMaterialRelation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(binaryFormalRelationEClass, BinaryFormalRelation.class, "BinaryFormalRelation", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getBinaryFormalRelation_Source(), this.getUniversal(), null, "source", null, 0, 1, BinaryFormalRelation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getBinaryFormalRelation_SourceLowerBound(), ecorePackage.getEInt(), "sourceLowerBound", null, 0, 1, BinaryFormalRelation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getBinaryFormalRelation_SourceUpperBound(), ecorePackage.getEInt(), "sourceUpperBound", null, 0, 1, BinaryFormalRelation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getBinaryFormalRelation_Name(), ecorePackage.getEString(), "name", null, 0, 1, BinaryFormalRelation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getBinaryFormalRelation_Target(), this.getUniversal(), null, "target", null, 0, 1, BinaryFormalRelation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getBinaryFormalRelation_TargetLowerBound(), ecorePackage.getEInt(), "targetLowerBound", null, 0, 1, BinaryFormalRelation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getBinaryFormalRelation_TargetUpperBound(), ecorePackage.getEInt(), "targetUpperBound", null, 0, 1, BinaryFormalRelation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(modeUniversalEClass, ModeUniversal.class, "ModeUniversal", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getModeUniversal_Name(), ecorePackage.getEString(), "name", null, 0, 1, ModeUniversal.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getModeUniversal_CharacterizedBy(), this.getCharacterization(), null, "characterizedBy", null, 0, -1, ModeUniversal.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(qualityUniversalEClass, QualityUniversal.class, "QualityUniversal", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getQualityUniversal_Name(), ecorePackage.getEString(), "name", null, 0, 1, QualityUniversal.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getQualityUniversal_Characterization(), this.getCharacterization(), null, "characterization", null, 0, 1, QualityUniversal.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getQualityUniversal_Datatypes(), this.getDataType(), null, "datatypes", null, 0, -1, QualityUniversal.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getQualityUniversal_CharacterizedBy(), this.getCharacterization(), null, "characterizedBy", null, 0, -1, QualityUniversal.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(nAryMaterialRelationEClass, nAryMaterialRelation.class, "nAryMaterialRelation", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getnAryMaterialRelation_DerivedFrom(), this.getRelatorUniversal(), null, "derivedFrom", null, 0, 1, nAryMaterialRelation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getnAryMaterialRelation_Name(), ecorePackage.getEString(), "name", null, 0, 1, nAryMaterialRelation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getnAryMaterialRelation_TargetRelata(), this.getExternallyDependentUniversal(), null, "targetRelata", null, 0, -1, nAryMaterialRelation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getnAryMaterialRelation_SourceLowerBound(), ecorePackage.getEInt(), "sourceLowerBound", null, 0, -1, nAryMaterialRelation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getnAryMaterialRelation_SourceUpperBound(), ecorePackage.getEInt(), "sourceUpperBound", null, 0, -1, nAryMaterialRelation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(nAryFormalRelationEClass, nAryFormalRelation.class, "nAryFormalRelation", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getnAryFormalRelation_Name(), ecorePackage.getEString(), "name", null, 0, 1, nAryFormalRelation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getnAryFormalRelation_TargetRelata(), this.getUniversal(), null, "targetRelata", null, 0, -1, nAryFormalRelation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getnAryFormalRelation_SourceLowerBound(), ecorePackage.getEInt(), "sourceLowerBound", null, 0, -1, nAryFormalRelation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getnAryFormalRelation_SourceUpperBound(), ecorePackage.getEInt(), "sourceUpperBound", null, 0, -1, nAryFormalRelation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(characterizationEClass, Characterization.class, "Characterization", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getCharacterization_SourceLowerBound(), ecorePackage.getEInt(), "sourceLowerBound", null, 0, 1, Characterization.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getCharacterization_SourceUpperBound(), ecorePackage.getEInt(), "sourceUpperBound", null, 0, 1, Characterization.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getCharacterization_Target(), this.getIntrinsicMomentUniversal(), null, "target", null, 0, 1, Characterization.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getCharacterization_TargetLowerBound(), ecorePackage.getEInt(), "targetLowerBound", null, 0, 1, Characterization.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getCharacterization_TargetUpperBound(), ecorePackage.getEInt(), "targetUpperBound", null, 0, 1, Characterization.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(mediationEClass, Mediation.class, "Mediation", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getMediation_SourceLowerBound(), ecorePackage.getEInt(), "sourceLowerBound", null, 0, 1, Mediation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getMediation_SourceUpperBound(), ecorePackage.getEInt(), "sourceUpperBound", null, 0, 1, Mediation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getMediation_Target(), this.getExternallyDependentUniversal(), null, "target", null, 0, 1, Mediation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getMediation_TargetLowerBound(), ecorePackage.getEInt(), "targetLowerBound", null, 0, 1, Mediation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getMediation_TargetUpperBound(), ecorePackage.getEInt(), "targetUpperBound", null, 0, 1, Mediation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(primitiveDataTypeTypeEClass, PrimitiveDataTypeType.class, "PrimitiveDataTypeType", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(dataTypeAttributeEClass, DataTypeAttribute.class, "DataTypeAttribute", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getDataTypeAttribute_IsOfType(), this.getDataType(), null, "isOfType", null, 0, 1, DataTypeAttribute.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getDataTypeAttribute_Name(), ecorePackage.getEString(), "name", null, 0, 1, DataTypeAttribute.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    // Create resource
    createResource(eNS_URI);
  }

} //DslPackageImpl
