/**
 * generated by Xtext 2.20.0
 */
package br.ufes.inf.ontouml.ontoumlprime.dsl.impl;

import br.ufes.inf.ontouml.ontoumlprime.dsl.DslPackage;
import br.ufes.inf.ontouml.ontoumlprime.dsl.ExternallyDependentUniversal;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Externally Dependent Universal</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ExternallyDependentUniversalImpl extends MinimalEObjectImpl.Container implements ExternallyDependentUniversal
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ExternallyDependentUniversalImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DslPackage.Literals.EXTERNALLY_DEPENDENT_UNIVERSAL;
  }

} //ExternallyDependentUniversalImpl
