/**
 * generated by Xtext 2.20.0
 */
package br.ufes.inf.ontouml.ontoumlprime.dsl.impl;

import br.ufes.inf.ontouml.ontoumlprime.dsl.DslPackage;
import br.ufes.inf.ontouml.ontoumlprime.dsl.GeneralizationSet;
import br.ufes.inf.ontouml.ontoumlprime.dsl.Universal;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EObjectResolvingEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Generalization Set</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link br.ufes.inf.ontouml.ontoumlprime.dsl.impl.GeneralizationSetImpl#isIsCovering <em>Is Covering</em>}</li>
 *   <li>{@link br.ufes.inf.ontouml.ontoumlprime.dsl.impl.GeneralizationSetImpl#getName <em>Name</em>}</li>
 *   <li>{@link br.ufes.inf.ontouml.ontoumlprime.dsl.impl.GeneralizationSetImpl#getSpecializedUniversal <em>Specialized Universal</em>}</li>
 *   <li>{@link br.ufes.inf.ontouml.ontoumlprime.dsl.impl.GeneralizationSetImpl#getSpecializingUniversals <em>Specializing Universals</em>}</li>
 * </ul>
 *
 * @generated
 */
public class GeneralizationSetImpl extends PackageableElementImpl implements GeneralizationSet
{
  /**
   * The default value of the '{@link #isIsCovering() <em>Is Covering</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isIsCovering()
   * @generated
   * @ordered
   */
  protected static final boolean IS_COVERING_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isIsCovering() <em>Is Covering</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isIsCovering()
   * @generated
   * @ordered
   */
  protected boolean isCovering = IS_COVERING_EDEFAULT;

  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getSpecializedUniversal() <em>Specialized Universal</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSpecializedUniversal()
   * @generated
   * @ordered
   */
  protected Universal specializedUniversal;

  /**
   * The cached value of the '{@link #getSpecializingUniversals() <em>Specializing Universals</em>}' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSpecializingUniversals()
   * @generated
   * @ordered
   */
  protected EList<Universal> specializingUniversals;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected GeneralizationSetImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DslPackage.Literals.GENERALIZATION_SET;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public boolean isIsCovering()
  {
    return isCovering;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setIsCovering(boolean newIsCovering)
  {
    boolean oldIsCovering = isCovering;
    isCovering = newIsCovering;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DslPackage.GENERALIZATION_SET__IS_COVERING, oldIsCovering, isCovering));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DslPackage.GENERALIZATION_SET__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Universal getSpecializedUniversal()
  {
    if (specializedUniversal != null && specializedUniversal.eIsProxy())
    {
      InternalEObject oldSpecializedUniversal = (InternalEObject)specializedUniversal;
      specializedUniversal = (Universal)eResolveProxy(oldSpecializedUniversal);
      if (specializedUniversal != oldSpecializedUniversal)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, DslPackage.GENERALIZATION_SET__SPECIALIZED_UNIVERSAL, oldSpecializedUniversal, specializedUniversal));
      }
    }
    return specializedUniversal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Universal basicGetSpecializedUniversal()
  {
    return specializedUniversal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setSpecializedUniversal(Universal newSpecializedUniversal)
  {
    Universal oldSpecializedUniversal = specializedUniversal;
    specializedUniversal = newSpecializedUniversal;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DslPackage.GENERALIZATION_SET__SPECIALIZED_UNIVERSAL, oldSpecializedUniversal, specializedUniversal));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<Universal> getSpecializingUniversals()
  {
    if (specializingUniversals == null)
    {
      specializingUniversals = new EObjectResolvingEList<Universal>(Universal.class, this, DslPackage.GENERALIZATION_SET__SPECIALIZING_UNIVERSALS);
    }
    return specializingUniversals;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case DslPackage.GENERALIZATION_SET__IS_COVERING:
        return isIsCovering();
      case DslPackage.GENERALIZATION_SET__NAME:
        return getName();
      case DslPackage.GENERALIZATION_SET__SPECIALIZED_UNIVERSAL:
        if (resolve) return getSpecializedUniversal();
        return basicGetSpecializedUniversal();
      case DslPackage.GENERALIZATION_SET__SPECIALIZING_UNIVERSALS:
        return getSpecializingUniversals();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case DslPackage.GENERALIZATION_SET__IS_COVERING:
        setIsCovering((Boolean)newValue);
        return;
      case DslPackage.GENERALIZATION_SET__NAME:
        setName((String)newValue);
        return;
      case DslPackage.GENERALIZATION_SET__SPECIALIZED_UNIVERSAL:
        setSpecializedUniversal((Universal)newValue);
        return;
      case DslPackage.GENERALIZATION_SET__SPECIALIZING_UNIVERSALS:
        getSpecializingUniversals().clear();
        getSpecializingUniversals().addAll((Collection<? extends Universal>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case DslPackage.GENERALIZATION_SET__IS_COVERING:
        setIsCovering(IS_COVERING_EDEFAULT);
        return;
      case DslPackage.GENERALIZATION_SET__NAME:
        setName(NAME_EDEFAULT);
        return;
      case DslPackage.GENERALIZATION_SET__SPECIALIZED_UNIVERSAL:
        setSpecializedUniversal((Universal)null);
        return;
      case DslPackage.GENERALIZATION_SET__SPECIALIZING_UNIVERSALS:
        getSpecializingUniversals().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case DslPackage.GENERALIZATION_SET__IS_COVERING:
        return isCovering != IS_COVERING_EDEFAULT;
      case DslPackage.GENERALIZATION_SET__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case DslPackage.GENERALIZATION_SET__SPECIALIZED_UNIVERSAL:
        return specializedUniversal != null;
      case DslPackage.GENERALIZATION_SET__SPECIALIZING_UNIVERSALS:
        return specializingUniversals != null && !specializingUniversals.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (isCovering: ");
    result.append(isCovering);
    result.append(", name: ");
    result.append(name);
    result.append(')');
    return result.toString();
  }

} //GeneralizationSetImpl
