/**
 * generated by Xtext 2.20.0
 */
package br.ufes.inf.ontouml.ontoumlprime.dsl.impl;

import br.ufes.inf.ontouml.ontoumlprime.dsl.DslPackage;
import br.ufes.inf.ontouml.ontoumlprime.dsl.MembershipRelation;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Membership Relation</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link br.ufes.inf.ontouml.ontoumlprime.dsl.impl.MembershipRelationImpl#isPartIsShareable <em>Part Is Shareable</em>}</li>
 * </ul>
 *
 * @generated
 */
public class MembershipRelationImpl extends MeronymicRelationImpl implements MembershipRelation
{
  /**
   * The default value of the '{@link #isPartIsShareable() <em>Part Is Shareable</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isPartIsShareable()
   * @generated
   * @ordered
   */
  protected static final boolean PART_IS_SHAREABLE_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isPartIsShareable() <em>Part Is Shareable</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isPartIsShareable()
   * @generated
   * @ordered
   */
  protected boolean partIsShareable = PART_IS_SHAREABLE_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected MembershipRelationImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DslPackage.Literals.MEMBERSHIP_RELATION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public boolean isPartIsShareable()
  {
    return partIsShareable;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setPartIsShareable(boolean newPartIsShareable)
  {
    boolean oldPartIsShareable = partIsShareable;
    partIsShareable = newPartIsShareable;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DslPackage.MEMBERSHIP_RELATION__PART_IS_SHAREABLE, oldPartIsShareable, partIsShareable));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case DslPackage.MEMBERSHIP_RELATION__PART_IS_SHAREABLE:
        return isPartIsShareable();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case DslPackage.MEMBERSHIP_RELATION__PART_IS_SHAREABLE:
        setPartIsShareable((Boolean)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case DslPackage.MEMBERSHIP_RELATION__PART_IS_SHAREABLE:
        setPartIsShareable(PART_IS_SHAREABLE_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case DslPackage.MEMBERSHIP_RELATION__PART_IS_SHAREABLE:
        return partIsShareable != PART_IS_SHAREABLE_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (partIsShareable: ");
    result.append(partIsShareable);
    result.append(')');
    return result.toString();
  }

} //MembershipRelationImpl
