/**
 * generated by Xtext 2.20.0
 */
package br.ufes.inf.ontouml.ontoumlprime.dsl.impl;

import br.ufes.inf.ontouml.ontoumlprime.dsl.DslPackage;
import br.ufes.inf.ontouml.ontoumlprime.dsl.ExternallyDependentUniversal;
import br.ufes.inf.ontouml.ontoumlprime.dsl.RelatorUniversal;
import br.ufes.inf.ontouml.ontoumlprime.dsl.nAryMaterialRelation;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EDataTypeEList;
import org.eclipse.emf.ecore.util.EObjectResolvingEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>nAry Material Relation</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link br.ufes.inf.ontouml.ontoumlprime.dsl.impl.nAryMaterialRelationImpl#getDerivedFrom <em>Derived From</em>}</li>
 *   <li>{@link br.ufes.inf.ontouml.ontoumlprime.dsl.impl.nAryMaterialRelationImpl#getName <em>Name</em>}</li>
 *   <li>{@link br.ufes.inf.ontouml.ontoumlprime.dsl.impl.nAryMaterialRelationImpl#getTargetRelata <em>Target Relata</em>}</li>
 *   <li>{@link br.ufes.inf.ontouml.ontoumlprime.dsl.impl.nAryMaterialRelationImpl#getSourceLowerBound <em>Source Lower Bound</em>}</li>
 *   <li>{@link br.ufes.inf.ontouml.ontoumlprime.dsl.impl.nAryMaterialRelationImpl#getSourceUpperBound <em>Source Upper Bound</em>}</li>
 * </ul>
 *
 * @generated
 */
public class nAryMaterialRelationImpl extends PackageableElementImpl implements nAryMaterialRelation
{
  /**
   * The cached value of the '{@link #getDerivedFrom() <em>Derived From</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDerivedFrom()
   * @generated
   * @ordered
   */
  protected RelatorUniversal derivedFrom;

  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getTargetRelata() <em>Target Relata</em>}' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTargetRelata()
   * @generated
   * @ordered
   */
  protected EList<ExternallyDependentUniversal> targetRelata;

  /**
   * The cached value of the '{@link #getSourceLowerBound() <em>Source Lower Bound</em>}' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSourceLowerBound()
   * @generated
   * @ordered
   */
  protected EList<Integer> sourceLowerBound;

  /**
   * The cached value of the '{@link #getSourceUpperBound() <em>Source Upper Bound</em>}' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSourceUpperBound()
   * @generated
   * @ordered
   */
  protected EList<Integer> sourceUpperBound;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected nAryMaterialRelationImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DslPackage.Literals.NARY_MATERIAL_RELATION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public RelatorUniversal getDerivedFrom()
  {
    if (derivedFrom != null && derivedFrom.eIsProxy())
    {
      InternalEObject oldDerivedFrom = (InternalEObject)derivedFrom;
      derivedFrom = (RelatorUniversal)eResolveProxy(oldDerivedFrom);
      if (derivedFrom != oldDerivedFrom)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, DslPackage.NARY_MATERIAL_RELATION__DERIVED_FROM, oldDerivedFrom, derivedFrom));
      }
    }
    return derivedFrom;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public RelatorUniversal basicGetDerivedFrom()
  {
    return derivedFrom;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setDerivedFrom(RelatorUniversal newDerivedFrom)
  {
    RelatorUniversal oldDerivedFrom = derivedFrom;
    derivedFrom = newDerivedFrom;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DslPackage.NARY_MATERIAL_RELATION__DERIVED_FROM, oldDerivedFrom, derivedFrom));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DslPackage.NARY_MATERIAL_RELATION__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<ExternallyDependentUniversal> getTargetRelata()
  {
    if (targetRelata == null)
    {
      targetRelata = new EObjectResolvingEList<ExternallyDependentUniversal>(ExternallyDependentUniversal.class, this, DslPackage.NARY_MATERIAL_RELATION__TARGET_RELATA);
    }
    return targetRelata;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<Integer> getSourceLowerBound()
  {
    if (sourceLowerBound == null)
    {
      sourceLowerBound = new EDataTypeEList<Integer>(Integer.class, this, DslPackage.NARY_MATERIAL_RELATION__SOURCE_LOWER_BOUND);
    }
    return sourceLowerBound;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<Integer> getSourceUpperBound()
  {
    if (sourceUpperBound == null)
    {
      sourceUpperBound = new EDataTypeEList<Integer>(Integer.class, this, DslPackage.NARY_MATERIAL_RELATION__SOURCE_UPPER_BOUND);
    }
    return sourceUpperBound;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case DslPackage.NARY_MATERIAL_RELATION__DERIVED_FROM:
        if (resolve) return getDerivedFrom();
        return basicGetDerivedFrom();
      case DslPackage.NARY_MATERIAL_RELATION__NAME:
        return getName();
      case DslPackage.NARY_MATERIAL_RELATION__TARGET_RELATA:
        return getTargetRelata();
      case DslPackage.NARY_MATERIAL_RELATION__SOURCE_LOWER_BOUND:
        return getSourceLowerBound();
      case DslPackage.NARY_MATERIAL_RELATION__SOURCE_UPPER_BOUND:
        return getSourceUpperBound();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case DslPackage.NARY_MATERIAL_RELATION__DERIVED_FROM:
        setDerivedFrom((RelatorUniversal)newValue);
        return;
      case DslPackage.NARY_MATERIAL_RELATION__NAME:
        setName((String)newValue);
        return;
      case DslPackage.NARY_MATERIAL_RELATION__TARGET_RELATA:
        getTargetRelata().clear();
        getTargetRelata().addAll((Collection<? extends ExternallyDependentUniversal>)newValue);
        return;
      case DslPackage.NARY_MATERIAL_RELATION__SOURCE_LOWER_BOUND:
        getSourceLowerBound().clear();
        getSourceLowerBound().addAll((Collection<? extends Integer>)newValue);
        return;
      case DslPackage.NARY_MATERIAL_RELATION__SOURCE_UPPER_BOUND:
        getSourceUpperBound().clear();
        getSourceUpperBound().addAll((Collection<? extends Integer>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case DslPackage.NARY_MATERIAL_RELATION__DERIVED_FROM:
        setDerivedFrom((RelatorUniversal)null);
        return;
      case DslPackage.NARY_MATERIAL_RELATION__NAME:
        setName(NAME_EDEFAULT);
        return;
      case DslPackage.NARY_MATERIAL_RELATION__TARGET_RELATA:
        getTargetRelata().clear();
        return;
      case DslPackage.NARY_MATERIAL_RELATION__SOURCE_LOWER_BOUND:
        getSourceLowerBound().clear();
        return;
      case DslPackage.NARY_MATERIAL_RELATION__SOURCE_UPPER_BOUND:
        getSourceUpperBound().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case DslPackage.NARY_MATERIAL_RELATION__DERIVED_FROM:
        return derivedFrom != null;
      case DslPackage.NARY_MATERIAL_RELATION__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case DslPackage.NARY_MATERIAL_RELATION__TARGET_RELATA:
        return targetRelata != null && !targetRelata.isEmpty();
      case DslPackage.NARY_MATERIAL_RELATION__SOURCE_LOWER_BOUND:
        return sourceLowerBound != null && !sourceLowerBound.isEmpty();
      case DslPackage.NARY_MATERIAL_RELATION__SOURCE_UPPER_BOUND:
        return sourceUpperBound != null && !sourceUpperBound.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(", sourceLowerBound: ");
    result.append(sourceLowerBound);
    result.append(", sourceUpperBound: ");
    result.append(sourceUpperBound);
    result.append(')');
    return result.toString();
  }

} //nAryMaterialRelationImpl
