/*
 * generated by Xtext 2.20.0
 */
package br.ufes.inf.ontouml.ontoumlprime;

import org.eclipse.xtext.conversion.IValueConverterService;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class DslRuntimeModule extends AbstractDslRuntimeModule {
	@Override
	public Class<? extends IValueConverterService> 
	    bindIValueConverterService() {
	    return OntoUMLPrimeValueConverterService.class;
	}
}
