/*
 * generated by Xtext 2.20.0
 */
package br.ufes.inf.ontouml.ontoumlprime.ide;


/**
 * Use this class to register ide components.
 */
public class DslIdeModule extends AbstractDslIdeModule {
}
